'use strict';

function showUrgent(message){const box=$('urgentBanner');box.textContent=message;box.classList.remove('hidden');clearTimeout(showUrgent._t);showUrgent._t=setTimeout(()=>box.classList.add('hidden'),5000);}
function statusText(){if(state.ended)return'Complete';if(!state.started)return'Not started';if(state.running)return'Running';return state.mode==='practice'?'Coached pause':'Paused';}
function renderSignoutAndRankings(){
  $('signoutCards').innerHTML=state.patientOrder.map(id=>`<article class="signout-card"><h3>${esc(state.patients[id].name)} · ${esc(state.patients[id].age)}</h3><p>${esc(state.patients[id].signout)}</p></article>`).join('');
  const ranks=(containerId,prefix)=>$(containerId).innerHTML=state.patientOrder.map(id=>`<label class="rank-row"><span><b>${esc(state.patients[id].name)}</b><small>${esc(state.patients[id].room)}</small></span><select id="${prefix}-${id}" aria-label="Rank ${esc(state.patients[id].name)}"><option value="">Rank…</option>${[1,2,3,4].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label>`).join('');
  ranks('initialRanking','initial-rank');ranks('finalRanking','final-rank');
  $('handoffFields').innerHTML=state.patientOrder.map(id=>`<section class="handoff-card"><h3>${esc(state.patients[id].name)}</h3>${[['illness','Illness severity'],['summary','Patient summary'],['actions','Action list / completed care'],['pending','Situation awareness / pending work'],['contingency','Synthesis and contingency plan']].map(([key,label])=>`<label>${label}<textarea id="handoff-${id}-${key}" rows="2"></textarea></label>`).join('')}</section>`).join('');
}
function renderTop(){
  $('clock').textContent=fmtTime(state.time);$('runState').textContent=statusText();$('modeState').textContent=state.mode==='assessment'?'Assessment':'Practice';$('pauseBtn').disabled=!state.started||state.ended;$('pauseBtn').textContent=state.running?'Pause':'Resume';$('endBtn').disabled=!state.started||state.ended;
  const staffText=['nurse','intern'].map(id=>`${id==='nurse'?'RN':'Intern'} ${state.staff[id].busyUntil>state.time?`busy ${fmtTime(state.staff[id].busyUntil-state.time)}`:'ready'}`).join(' · ');$('staffState').textContent=staffText;
  const paused=state.started&&!state.running&&!state.ended;if(paused){$('pauseBanner').textContent=state.mode==='assessment'?'Assessment paused: all clinical actions are disabled.':'Practice coached pause: exploration is allowed, but the run is non-comparable and scenario time does not advance.';$('pauseBanner').classList.remove('hidden');}else $('pauseBanner').classList.add('hidden');
}
function renderBoard(){
  $('patientBoard').innerHTML=state.patientOrder.map(id=>{const p=state.patients[id];return`<button class="patient-card ${state.selectedId===id?'active':''}" data-patient="${id}" ${!state.started||state.ended?'disabled':''}><span class="dot ${acuityClass(p)}" aria-hidden="true"></span><b>${esc(p.name)}</b><span>${esc(p.age)} · ${esc(p.room)}</span><span>${esc(p.chief)}</span><span class="acuity-label">${esc(acuityText(p))}</span></button>`;}).join('');
  document.querySelectorAll('[data-patient]').forEach(btn=>btn.onclick=()=>{state.selectedId=btn.dataset.patient;state.patients[state.selectedId].reviewed=true;renderAll();});
  const open=state.pages.filter(p=>p.resolvedAt===null).length;$('openPagesBadge').textContent=`${open} open page${open===1?'':'s'}`;$('boardInstruction').textContent=state.started?'Allocate attention, delegate parallel work, and reassess response.':'Commit an initial acuity ranking before opening the workspace.';
}
function selected(){return state.selectedId?state.patients[state.selectedId]:null;}
function displayedVitals(p){return p.observedVitals.length?p.observedVitals[p.observedVitals.length-1]:{time:0,source:'Initial charted vital signs',...p.initial};}
function formatVital(key,value){if(key==='Lactate')return Number(value).toFixed(1);if(['HR','RR','SpO2'].includes(key))return Math.round(Number(value));if(key==='Temp')return Number(value).toFixed(1);return value;}
function renderVitalsAndTrend(){
  const p=selected();if(!p){$('vitals').innerHTML='<p class="placeholder">No patient selected.</p>';$('trendChart').innerHTML='';$('trendLabel').textContent='No measurements';return;}
  const v=displayedVitals(p);$('vitals').innerHTML=Object.entries(v).filter(([k])=>!['time','source'].includes(k)).map(([k,val])=>`<div class="vital"><small>${esc(k)}</small><b>${esc(formatVital(k,val))}</b></div>`).join('');
  const obs=p.observedVitals.slice(-10);if(!obs.length){$('trendChart').innerHTML='<p class="placeholder">Repeat vital signs to create an observed trend.</p>';$('trendLabel').textContent='No learner-observed trend';return;}
  const values=obs.map(x=>Number(x.HR));const min=Math.min(...values)-5,max=Math.max(...values)+5,span=Math.max(1,max-min);const width=360,height=70;const points=values.map((val,i)=>`${obs.length===1?width/2:i/(obs.length-1)*width},${height-(val-min)/span*(height-14)-7}`).join(' ');
  $('trendChart').innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Observed heart-rate trend"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3"/>${values.map((val,i)=>{const x=obs.length===1?width/2:i/(obs.length-1)*width,y=height-(val-min)/span*(height-14)-7;return`<circle cx="${x}" cy="${y}" r="4" fill="currentColor"><title>${fmtTime(obs[i].time)} HR ${Math.round(val)}</title></circle>`;}).join('')}</svg><div class="workflow">${obs.map(x=>`<span class="step done">${fmtTime(x.time)} HR ${Math.round(Number(x.HR))} · SpO₂ ${Math.round(Number(x.SpO2))}%${state.selectedId==='maya'?` · lactate ${Number(x.Lactate).toFixed(1)}`:''}</span>`).join('')}</div>`;$('trendLabel').textContent=`Observed HR · ${obs.length} measurement${obs.length===1?'':'s'}`;
}
function renderWorkspace(){
  const p=selected();$('patientWorkspace').classList.toggle('muted-workspace',!p);
  if(!p){$('patientTitle').textContent='No patient selected';$('patientSubtitle').textContent='Select a patient.';$('patientState').textContent='Unreviewed';renderVitalsAndTrend();for(const id of ['historyTranscript','examFindings','reasoningHistory','orderResults','placedOrders','teamTranscript'])if($(id))$(id).innerHTML='<p class="placeholder">No patient selected.</p>';return;}
  $('patientTitle').textContent=`${p.name} — ${p.room}`;$('patientSubtitle').textContent=`${p.age} · ${p.weight} · ${p.chief}`;$('patientState').textContent=acuityText(p);$('patientState').className=`patient-state ${acuityClass(p)==='critical'?'criticalText':acuityClass(p)==='warning'?'warnText':'goodText'}`;renderVitalsAndTrend();renderHistory();renderExam();renderReasoning();renderOrders();renderTeam();
}
function renderHistory(){const p=selected();$('historyTranscript').innerHTML=p.historyLog.length?p.historyLog.slice().reverse().map(x=>`<div class="entry"><div class="entry-meta">${fmtTime(x.time)} · ${esc(x.source)}</div><b>Q: ${esc(x.question)}</b><p>A: ${esc(x.answer)}</p></div>`).join(''):'<p class="placeholder">No focused history obtained.</p>';}
function renderExam(){const p=selected();$('examMenu').innerHTML=p.exams.map(ex=>`<button class="component clinical-control" data-exam="${ex.id}"><b>${esc(ex.label)}</b><small>${fmtTime(ex.cost)}${p.examCounts[ex.id]?` · repeated ${p.examCounts[ex.id]}×`:''}</small></button>`).join('');document.querySelectorAll('[data-exam]').forEach(btn=>btn.onclick=()=>performExam(btn.dataset.exam));$('examFindings').innerHTML=p.examLog.length?p.examLog.slice().reverse().map(x=>`<div class="entry"><div class="entry-meta">${fmtTime(x.time)} · ${esc(x.label)} · assessment ${x.count}</div><p>${esc(x.finding)}</p></div>`).join(''):'<p class="placeholder">No examination findings yet.</p>';}
function renderReasoning(){const p=selected();$('diagnosisChoice').innerHTML='<option value="">Choose a provisional diagnosis…</option>'+p.diagnosisChoices.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('reasoningHistory').innerHTML=p.reasoning.length?p.reasoning.slice().reverse().map(x=>`<div class="reasoning-entry"><div class="entry-meta">${fmtTime(x.time)} · ${x.confidence}% confidence</div><b>${esc(x.diagnosis)}</b><p>${esc(x.problem)}</p><p><strong>Plan:</strong> ${esc(x.plan)}</p></div>`).join(''):'<p class="placeholder">No reasoning commitment yet.</p>';}
function renderOrders(){
  const p=selected(),query=$('orderSearch').value.trim().toLowerCase();if(query.length<2)$('orderResults').innerHTML='<p class="placeholder">Type at least two characters.</p>';else{const matches=p.catalog.filter(x=>orderVisible(state.selectedId,x)&&(x.name.toLowerCase().includes(query)||x.type.toLowerCase().includes(query)));$('orderResults').innerHTML=matches.length?matches.map(x=>`<button class="order-option clinical-control" data-order="${x.id}" ${currentOrder(state.selectedId,x.id)?'disabled':''}><b>${esc(x.name)}</b><small>${esc(x.type)} · attention ${fmtTime(x.attention)} · process ${fmtTime(x.process)}</small></button>`).join(''):'<p class="placeholder">No matching order.</p>';document.querySelectorAll('[data-order]').forEach(btn=>btn.onclick=()=>placeOrder(btn.dataset.order));}
  $('placedOrders').innerHTML=p.orders.length?p.orders.slice().reverse().map(o=>`<div class="order-card"><b>${esc(o.name)}</b><div class="entry-meta">Placed ${fmtTime(o.placedAt)} · ${o.status}</div><div class="workflow"><span class="step done">Placed</span><span class="step ${o.availableAt!==null?'done':''}">Available</span><span class="step ${o.reviewedAt!==null?'done':''}">Reviewed</span><span class="step ${o.interpretedAt!==null?'done':''}">Interpreted</span><span class="step ${o.actedAt!==null?'done':''}">Acted</span></div></div>`).join(''):'<p class="placeholder">No orders placed.</p>';
}
function renderTeam(){
  selected();$('teamRoles').innerHTML=[['nurse','Bedside nurse'],['intern','Intern'],['attending','Supervising attending'],['cardiology','Cardiology / cardiac ICU'],['parent','Parent or caregiver']].map(([id,label])=>`<button class="team-role ${state.teamRole===id?'primary':''}" data-role="${id}"><b>${label}</b></button>`).join('');document.querySelectorAll('[data-role]').forEach(btn=>btn.onclick=()=>selectTeamRole(btn.dataset.role));
  $('teamTranscript').innerHTML=state.teamMessages.filter(x=>x.patientId===state.selectedId).length?state.teamMessages.filter(x=>x.patientId===state.selectedId).slice().reverse().map(x=>`<div class="entry"><div class="entry-meta">${fmtTime(x.time)} · ${esc(x.role)}</div><p><b>You:</b> ${esc(x.message)}</p><p><b>Response:</b> ${esc(x.reply)}</p></div>`).join(''):'<p class="placeholder">No team communication for this patient.</p>';
  $('confirmReadbackBtn').classList.toggle('hidden',!state.pendingReadback||state.pendingReadback.patientId!==state.selectedId);$('delegationMenu').innerHTML=delegationOptions(state.selectedId).map(x=>`<button class="delegate-option clinical-control" data-delegate="${x.id}" ${state.staff[x.staff].busyUntil>state.time?'disabled':''}><b>${esc(x.label)}</b><small>${x.staff} · process ${fmtTime(x.duration)}</small></button>`).join('');document.querySelectorAll('[data-delegate]').forEach(btn=>btn.onclick=()=>delegateTask(btn.dataset.delegate));
}
function renderPages(){
  const pages=state.pages.slice().sort((a,b)=>(a.resolvedAt===null?0:1)-(b.resolvedAt===null?0:1)||b.createdAt-a.createdAt);$('pages').innerHTML=pages.length?pages.map(p=>`<article class="page-card ${p.urgent?'urgent':''}"><div class="page-meta">${fmtTime(p.createdAt)} · ${esc(state.patients[p.patientId].name)} · ${p.urgent?'urgent':'routine'}</div><b>${esc(p.title)}</b><p>${esc(p.text)}</p><div class="workflow"><span class="step ${p.ackAt!==null?'done':''}">Acknowledged${p.ackAt!==null?` ${fmtTime(p.ackAt)}`:''}</span><span class="step ${p.responseAt!==null?'done':''}">Responded</span><span class="step ${p.resolvedAt!==null?'done':''}">Resolved</span></div>${p.ackAt===null?`<button class="clinical-control" data-page="${p.id}">Acknowledge and assess · 0:05</button>`:''}</article>`).join(''):'<p class="placeholder">No pages yet.</p>';document.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>acknowledgePage(btn.dataset.page));const open=state.pages.filter(p=>p.resolvedAt===null).length;$('pageCount').textContent=`${open} open`;
}
function renderResults(){
  const all=Object.entries(state.patients).flatMap(([pid,p])=>p.results.map(r=>({...r,pid,name:p.name}))).sort((a,b)=>b.availableAt-a.availableAt);$('results').innerHTML=all.length?all.map(r=>`<article class="result-card ${r.reviewedAt!==null?'reviewed':'available'} ${r.tone==='bad'||r.tone==='critical'?'critical':''}"><div class="entry-meta">${fmtTime(r.availableAt)} · ${esc(r.name)}</div><b>${esc(r.title)}</b><p>${r.reviewedAt!==null?esc(r.text):'Result available — open to review.'}</p><div class="workflow"><span class="step done">Available</span><span class="step ${r.reviewedAt!==null?'done':''}">Reviewed</span><span class="step ${r.interpretedAt!==null?'done':''}">Interpreted</span><span class="step ${r.actedAt!==null?'done':''}">Acted</span></div>${r.reviewedAt===null?`<button class="clinical-control" data-review-result="${r.pid}|${r.id}">Review · 0:10</button>`:r.requiresInterpretation&&r.interpretedAt===null?`<button class="clinical-control" data-interpret-result="${r.pid}|${r.id}">Document interpretation · 0:10</button>`:''}</article>`).join(''):'<p class="placeholder">No results available.</p>';document.querySelectorAll('[data-review-result]').forEach(btn=>btn.onclick=()=>{const [pid,rid]=btn.dataset.reviewResult.split('|');reviewResult(pid,rid);});document.querySelectorAll('[data-interpret-result]').forEach(btn=>btn.onclick=()=>{const [pid,rid]=btn.dataset.interpretResult.split('|');interpretResult(pid,rid);});$('pendingCount').textContent=`${state.processes.filter(p=>p.status==='pending').length} pending`;
}
function renderLedgerTimeline(){
  $('attentionTotal').textContent=`${fmtTime(state.totalAttention)} used`;$('attentionLedger').innerHTML=state.ledger.length?state.ledger.map(x=>`<div class="ledger-entry"><div class="entry-meta">${fmtTime(x.start)}–${fmtTime(x.end)}${x.paused?' · coached pause':''}</div><b>${esc(x.label)}</b>${x.patientId?`<span> · ${esc(state.patients[x.patientId].name)}</span>`:''}</div>`).join(''):'<p class="placeholder">No learner attention spent.</p>';$('eventCount').textContent=`${state.timeline.length} events`;$('timeline').innerHTML=state.timeline.length?state.timeline.map(x=>`<div class="timeline-entry"><div class="entry-meta">${fmtTime(x.time)}${x.patientId?` · ${esc(state.patients[x.patientId].name)}`:''}</div><p>${esc(x.text)}</p></div>`).join(''):'<p class="placeholder">The shift has not started.</p>';
}
function applyInteractionGate(){
  const enabled=canInteract();document.querySelectorAll('.clinical-control').forEach(el=>{if(!el.dataset.originalDisabled)el.dataset.originalDisabled=el.disabled?'1':'0';if(!enabled)el.disabled=true;else if(el.dataset.originalDisabled!=='1')el.disabled=false;});
  $('askHistoryBtn').disabled=!enabled||!state.selectedId;$('repeatVitalsBtn').disabled=!enabled||!state.selectedId;$('commitReasoningBtn').disabled=!enabled||!state.selectedId;$('sendTeamBtn').disabled=!enabled||!state.selectedId||!state.teamRole;
  const inputDisabled=!enabled;for(const id of ['historyInput','historySource','problemRepresentation','diagnosisChoice','alternatives','immediatePlan','confidence','orderSearch','teamMessage'])if($(id))$(id).disabled=inputDisabled||!state.selectedId;
}
function renderDynamic(){renderTop();renderVitalsAndTrend();renderPages();renderResults();renderLedgerTimeline();applyInteractionGate();}
function renderAll(){renderTop();renderBoard();renderWorkspace();renderPages();renderResults();renderLedgerTimeline();applyInteractionGate();}
