'use strict';
function askHistory(question,source){const pid=state.selectedId;if(!pid||!canInteract()||!question.trim())return;const p=state.patients[pid];if(!spendAttention(20,`Focused ${source} history`,pid))return;const text=question.trim().toLowerCase();let answer='I do not have additional information about that.',category='other',disconfirming=false;for(const [key,item] of Object.entries(p.history)){if(hasTerms(text,item.terms)){answer=item[source]||item.parent;category=key;disconfirming=!!item.disconfirming;break;}}p.historyLog.push({time:state.time,source,question:question.trim(),answer,category,disconfirming});addTimeline(`History obtained: ${category}.`,pid,'history',{category,disconfirming});markPageResponse(pid);renderAll();}
function currentPatientState(pid){const p=state.patients[pid];if(p.flags.postTreatment||p.flags.stabilized||p.flags.responding)return'postTreatment';if(p.flags.deteriorating||p.flags.critical||p.flags.arrest)return'deteriorating';return'default';}
function performExam(examId){const pid=state.selectedId;if(!pid||!canInteract())return;const p=state.patients[pid],exam=p.exams.find(x=>x.id===examId);if(!exam)return;const repeat=(p.examCounts[examId]||0)>0;if(!spendAttention(exam.attention,`${exam.label}${repeat?' reassessment':''}`,pid))return;const key=currentPatientState(pid),finding=exam.findings[key]||exam.findings.default;p.examCounts[examId]=(p.examCounts[examId]||0)+1;p.examLog.push({time:state.time,examId,label:exam.label,finding,count:p.examCounts[examId],disconfirming:!!exam.disconfirming});addTimeline(`Examination: ${exam.label}.`,pid,'exam',{examId,disconfirming:!!exam.disconfirming});markPageResponse(pid);renderAll();}
function repeatVitals(){const pid=state.selectedId;if(!pid||!canInteract())return;if(!spendAttention(20,'Repeat full vital signs',pid))return;state.patients[pid].observedVitals.push({time:state.time,source:'Repeat vital signs',...clone(state.patients[pid].vitals)});addTimeline('Repeat vital signs recorded.',pid,'observation');markPageResponse(pid);renderAll();}
function commitReasoning(payload){const pid=state.selectedId;if(!pid||!canInteract())return false;if(!payload.problem||!payload.diagnosis||!payload.plan){showUrgent('Complete the problem representation, leading diagnosis, and immediate plan.');return false;}if(!spendAttention(30,'Diagnostic reasoning commitment',pid))return false;state.patients[pid].reasoning.push({time:state.time,...payload});addTimeline(`Reasoning committed: ${payload.diagnosis} (${payload.confidence}% confidence).`,pid,'reasoning');renderAll();return true;}
function placeOrder(orderId){const pid=state.selectedId;if(!pid||!canInteract())return;const p=state.patients[pid],item=p.orders.find(x=>x.id===orderId);if(!item)return;if(orderRecord(pid,orderId)){showUrgent(`${item.name} has already been ordered.`);return;}if(item.requiresReasoning&&!p.reasoning.length){showUrgent('Commit a provisional diagnosis and immediate plan before disease-specific treatment.');return;}if(!spendAttention(item.attention,`Order: ${item.name}`,pid))return;p.ordersPlaced.push({...clone(item),placedAt:state.time,status:'pending',availableAt:null});scheduleProcess({kind:'order',patientId:pid,orderId,due:state.time+item.process});addTimeline(`Order placed: ${item.name}.`,pid,'order');markPageResponse(pid);renderAll();}
function completeOrder(pid,orderId){const p=state.patients[pid],order=orderRecord(pid,orderId);if(!order||order.status!=='pending')return;order.status='available';order.availableAt=state.time;let resultText=order.result;if(pid==='maya'&&orderId==='gas')resultText=`Metabolic acidosis is present; lactate is ${Number(p.vitals.Lactate).toFixed(1)} mmol/L.`;addResult(pid,orderId,order.name,resultText,order.tone||'neutral',!!order.requiresInterpretation);applyEffects(pid,order);renderAll();}
function applyEffects(pid,order){const p=state.patients[pid];for(const effect of order.effects||[])p.flags[effect.flag]=effect.value;if(pid==='maya'&&order.id==='pge'){p.flags.pgeStartedAt=state.time;for(const result of p.results)if(['echo','gas'].includes(result.orderId)&&result.actedAt==null)result.actedAt=state.time;if(!p.flags.airwayReady)scheduleProcess({kind:'special',special:'pge-apnea',due:state.time+45});}if(pid==='maya'&&order.id==='airway'&&p.flags.pgeApnea){p.flags.pgeApnea=false;p.flags.critical=false;p.vitals.SpO2=92;p.vitals.HR=148;state.flags.pgeApneaResolved=true;addTimeline('Immediate ventilatory support resolves the prostaglandin-associated apnea.','maya','rescue');resolvePages('maya');}if(pid==='maya'&&order.id==='bigbolus'){p.vitals.RR=Math.min(82,Number(p.vitals.RR)+8);p.vitals.BP='54/30';p.vitals.Lactate=Math.min(8,Number(p.vitals.Lactate)+.5);}if(pid==='eli'&&['oxygen','hfnc'].includes(order.id))resolvePages('eli');if(pid==='nora'&&order.id==='antibiotics')for(const result of p.results)if(['reviewculture','speciation'].includes(result.orderId)&&result.actedAt==null)result.actedAt=state.time;if(pid==='nora'&&order.id==='admit'&&p.flags.antibioticsStarted)resolvePages('nora');if(pid==='jamal'&&order.id==='family')resolvePages('jamal');}
function reviewResult(pid,resultId){if(!canInteract())return;const result=state.patients[pid].results.find(r=>r.id===resultId);if(!result||result.reviewedAt!=null)return;if(!spendAttention(10,`Review result: ${result.title}`,pid))return;result.reviewedAt=state.time;const order=orderRecord(pid,result.orderId);if(order)order.status='reviewed';markPageResponse(pid);if(pid==='nora'&&result.orderId==='reviewculture')state.flags.noraJudgmentPrompt=true;renderAll();}
function interpretResult(pid,resultId){if(!canInteract())return;const result=state.patients[pid].results.find(r=>r.id===resultId);if(!result||result.reviewedAt==null||result.interpretedAt!=null)return;if(!spendAttention(15,`Interpret result: ${result.title}`,pid))return;result.interpretedAt=state.time;const order=orderRecord(pid,result.orderId);if(order)order.status='interpreted';addTimeline(`Result interpreted: ${result.title}.`,pid,'interpretation');renderAll();}
function submitNoraJudgment(value,confidence){if(!canInteract()||state.noraJudgment)return;if(!spendAttention(20,'Provisional pathogen-versus-contaminant judgment','nora'))return;state.noraJudgment={value,confidence:Number(confidence),time:state.time};state.flags.noraJudgmentMade=true;state.flags.noraJudgmentPrompt=false;addTimeline(`Nora provisional culture judgment: ${value} (${confidence}% confidence).`,'nora','reasoning');scheduleProcess({kind:'special',special:'nora-speciation',due:state.time+90});renderAll();}
function sendTeamMessage(role,message){const pid=state.selectedId;if(!pid||!canInteract()||!role||!message.trim())return;if(!spendAttention(30,`Communicate with ${role}`,pid))return;const entry={time:state.time,patientId:pid,role,message:message.trim(),readback:false};state.patients[pid].teamMessages.push(entry);state.pendingReadback=entry;addTimeline(`Message sent to ${role}.`,pid,'communication');markPageResponse(pid);renderAll();}
function confirmReadback(){if(!canInteract()||!state.pendingReadback)return;if(!spendAttention(10,'Confirm closed-loop read-back',state.pendingReadback.patientId))return;state.pendingReadback.readback=true;addTimeline(`Read-back confirmed with ${state.pendingReadback.role}.`,state.pendingReadback.patientId,'readback');if(state.pendingReadback.patientId==='maya'&&['cardiology','attending'].includes(state.pendingReadback.role))resolvePages('maya');state.pendingReadback=null;renderAll();}
function selectPatient(pid){if(!state.started||state.ended||!state.patients[pid])return;state.selectedId=pid;renderAll();}
function togglePause(){if(!state.started||state.ended)return;state.running=!state.running;if(!state.running)state.pauseCount+=1;addTimeline(state.running?'Simulation resumed.':`Simulation paused in ${state.mode} mode.`,null,'system');renderAll();}
function startShift(ranking,mode){state.mode=mode;state.initialRanking=ranking;state.started=true;state.running=true;addTimeline(`Shift accepted in ${mode} mode. Initial acuity ranking committed.`,null,'start');hidePrebrief();renderAll();}
function openEndShift(){if(!state.started||state.ended)return;state.running=false;renderEndModal();}
function completeShift(finalRanking,handoffs){state.finalRanking=finalRanking;state.handoffs=handoffs;state.running=false;state.ended=true;state.endReason='Shift completed by learner.';addTimeline('End-of-shift I-PASS completed.',null,'handoff');finalizeAttempt();}
function autoEnd(reason){if(state.ended)return;state.running=false;state.ended=true;state.endReason=reason;finalizeAttempt();}
