'use strict';
function formatVital(k,v){if(v==null)return'—';if(k==='Lactate'||k==='Temp')return Number(v).toFixed(1);if(!Number.isFinite(Number(v)))return String(v);return String(Math.round(Number(v)*10)/10);}
function showPrebrief(){$('prebrief').classList.remove('hidden');$('debrief').classList.add('hidden');$('endModal').classList.add('hidden');renderPrebrief();}
function hidePrebrief(){$('prebrief').classList.add('hidden');}
function hideEndModal(){$('endModal').classList.add('hidden');}
function showDebrief(){$('debrief').classList.remove('hidden');renderDebrief();}
function renderPrebrief(){$('caseDescription').textContent=state.caseData.description;$('prebriefObjectives').innerHTML=state.caseData.objectives.map(o=>`<div class="objective"><b>${esc(o.label)}</b><div>${esc(o.description)}</div></div>`).join('');$('signoutCards').innerHTML=state.patientOrder.map(id=>{const p=state.patients[id];return`<div class="signout-card"><b>${esc(p.name)}</b><div class="muted">${esc(p.age)} · ${esc(p.room)}</div><p>${esc(p.signout)}</p></div>`;}).join('');$('initialRanking').innerHTML=state.patientOrder.map(id=>rankingControl('initial',id)).join('');$('prebriefError').textContent='';}
function rankingControl(prefix,id){const p=state.patients[id];return`<div class="ranking-row"><b>${esc(p.name)}</b><select id="${prefix}-rank-${id}" aria-label="${esc(p.name)} acuity rank"><option value="">Rank</option>${[1,2,3,4].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></div>`;}
function readRanking(prefix){const out={};for(const id of state.patientOrder)out[id]=Number($(`${prefix}-rank-${id}`).value)||0;return out;}
function validRanking(r){const v=Object.values(r);return v.every(x=>x>=1&&x<=4)&&new Set(v).size===4;}
function renderAll(){if(!state)return;renderHeader();renderObjectives();renderBoard();renderWorkspace();renderPages();renderLedger();renderAttemptHistory();if(state.ended&&!$('debrief').classList.contains('hidden'))renderDebrief();}
function renderDynamic(){renderHeader();renderBoard();renderVitals();renderPages();renderLedger();}
function renderHeader(){$('clock').textContent=fmtTime(state.time);if($('clockLeft')){const left=state.started&&!state.ended?clinicalTimeRemaining():null;$('clockLeft').textContent=state.flags?.handoffForced?'Handoff':(left==null?'—':fmtTime(left));$('clockLeft').className=left!=null&&left<=120?'low':'';}$('modeState').textContent=state.mode==='assessment'?'Assessment':'Practice';$('attemptState').textContent=`${state.attemptNumber} · ${state.variant.id}`;$('runState').textContent=state.ended?'Ended':!state.started?'Prebrief':state.running?'Running':state.mode==='practice'?'Practice pause':'Paused';$('pauseBtn').disabled=!state.started||state.ended;$('pauseBtn').textContent=state.running?'Pause':'Resume';$('endBtn').disabled=!state.started||state.ended;const blocked=state.started&&!state.ended&&!canInteract();$('workspace').classList.toggle('disabled-area',!state.started||blocked);$('boardPrompt').textContent=!state.started?'Commit an initial acuity ranking before opening the workspace.':blocked?'Assessment pause: clinical controls are disabled.':'Attention costs continue while physiology evolves.';}
function renderObjectives(){$('objectiveCount').textContent=state.caseData.objectives.length;$('objectiveList').innerHTML=state.caseData.objectives.map(o=>`<div class="objective"><b>${esc(o.id)} · ${esc(o.label)}</b><div>${esc(o.description)}</div></div>`).join('');}
function patientStateLabel(id){const p=state.patients[id];if(p.flags.arrest)return'Arrest';if(p.flags.critical)return'Critical';if(p.flags.stabilized)return'Stabilizing';if(p.flags.deteriorating)return'Deteriorating';if(p.historyLog.length||p.examLog.length||p.ordersPlaced.length)return'In progress';return'Unreviewed';}
function renderBoard(){$('patientBoard').innerHTML=state.patientOrder.map(id=>{const p=state.patients[id];return`<button class="patient-card ${state.selectedId===id?'active':''}" data-patient="${id}" ${!state.started||state.ended?'disabled':''}><h3>${esc(p.name)}</h3><p>${esc(p.age)} · ${esc(p.room)}</p><p>${esc(p.signout.slice(0,95))}${p.signout.length>95?'…':''}</p><div class="state">${esc(patientStateLabel(id))}</div></button>`;}).join('');document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>selectPatient(b.dataset.patient));const open=state.pages.filter(p=>p.resolvedAt==null).length;$('pageBadge').textContent=`${open} open page${open===1?'':'s'}`;}
function renderWorkspace(){const id=state.selectedId;if(!id){$('patientTitle').textContent='No patient selected';$('patientSubtitle').textContent='Select a patient after accepting sign-out.';$('patientStatus').textContent='Unreviewed';$('vitals').innerHTML='';$('trendStrip').textContent='No observations yet.';return;}const p=state.patients[id];$('patientTitle').textContent=`${p.name} — ${p.age}`;$('patientSubtitle').textContent=`${p.room} · ${p.weightKg!=null?`${p.weightKg} kg · `:''}${p.signout}`;$('patientStatus').textContent=patientStateLabel(id);renderVitals();renderHistory();renderExam();renderReasoning();renderOrders();renderTeam();renderResults();renderTabs();}
function renderTabs(){document.querySelectorAll('.tabs [role=tab]').forEach(b=>{const active=b.dataset.tab===state.activeTab;b.setAttribute('aria-selected',String(active));$(`tab-${b.dataset.tab}`).hidden=!active;});}
function renderVitals(){if(!state.selectedId)return;const p=state.patients[state.selectedId];$('vitals').innerHTML=Object.entries(p.vitals).map(([k,v])=>`<div class="vital"><small>${esc(k)}</small><strong>${esc(formatVital(k,v))}</strong></div>`).join('');const obs=p.observedVitals.slice(-4);$('trendStrip').innerHTML=obs.map(o=>`<span><b>${fmtTime(o.time)}</b> HR ${formatVital('HR',o.HR)} · RR ${formatVital('RR',o.RR)} · SpO2 ${formatVital('SpO2',o.SpO2)} · BP ${esc(o.BP)}</span>`).join(' &nbsp;→&nbsp; ');}
function clinicalDisabled(){return!canInteract();}
function renderHistory(){const p=state.patients[state.selectedId];$('askBtn').disabled=clinicalDisabled();$('historyLog').innerHTML=p.historyLog.length?p.historyLog.slice().reverse().map(x=>`<div class="feed-item"><small>${fmtTime(x.time)} · ${esc(x.source)}</small><b>${esc(x.question)}</b><div>${esc(x.answer)}</div></div>`).join(''):'<p class="muted">No focused history obtained.</p>';}
function renderExam(){const p=state.patients[state.selectedId];$('repeatVitalsBtn').disabled=clinicalDisabled();$('examMenu').innerHTML=p.exams.map(e=>`<button class="action-card" data-exam="${e.id}" ${clinicalDisabled()?'disabled':''}><b>${esc(e.label)}</b><small>${fmtTime(e.attention)} attention · completed ${p.examCounts[e.id]||0} time(s)</small></button>`).join('');document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>performExam(b.dataset.exam));$('examLog').innerHTML=p.examLog.length?p.examLog.slice().reverse().map(x=>`<div class="feed-item"><small>${fmtTime(x.time)} · attempt ${x.count}</small><b>${esc(x.label)}</b><div>${esc(x.finding)}</div></div>`).join(''):'<p class="muted">No examination findings recorded.</p>';}
function renderReasoning(){const p=state.patients[state.selectedId],current=$('diagnosisSelect').value;$('diagnosisSelect').innerHTML='<option value="">Select a leading diagnosis</option>'+p.diagnosisChoices.map(d=>`<option ${d===current?'selected':''}>${esc(d)}</option>`).join('');$('commitBtn').disabled=clinicalDisabled();$('reasoningLog').innerHTML=p.reasoning.length?p.reasoning.slice().reverse().map(r=>`<div class="feed-item"><small>${fmtTime(r.time)} · ${r.confidence}% confidence</small><b>${esc(r.diagnosis)}</b><div>${esc(r.problem)}</div><div class="muted">Plan: ${esc(r.plan)}</div></div>`).join(''):'<p class="muted">No reasoning commitment recorded.</p>';}
function renderOrders(){const p=state.patients[state.selectedId],q=$('orderSearch').value.trim().toLowerCase(),items=p.orders.filter(o=>!q||`${o.name} ${o.type}`.toLowerCase().includes(q));$('orderMenu').innerHTML=items.map(o=>{const placed=!!orderRecord(state.selectedId,o.id);return`<button class="action-card" data-order="${o.id}" ${clinicalDisabled()||placed?'disabled':''}><b>${esc(o.name)}</b><small>${esc(o.type)} · ${fmtTime(o.attention)} attention · ${fmtTime(o.process)} process${placed?' · placed':''}</small></button>`;}).join('')||'<p class="muted">No matching orders.</p>';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>placeOrder(b.dataset.order));$('orderLog').innerHTML=p.ordersPlaced.length?p.ordersPlaced.slice().reverse().map(o=>`<div class="feed-item"><small>${fmtTime(o.placedAt)} · ${esc(o.type)}</small><b>${esc(o.name)}</b><div>Status: ${esc(o.status)}</div></div>`).join(''):'<p class="muted">No orders placed.</p>';}
function renderTeam(){const p=state.patients[state.selectedId];$('roleMenu').innerHTML=TEAM_ROLES.map(r=>`<button data-role="${r.id}" class="${state.teamRole===r.id?'active':''}" ${clinicalDisabled()?'disabled':''}>${esc(r.label)}</button>`).join('');document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.teamRole=b.dataset.role;renderTeam();});$('sendTeamBtn').disabled=clinicalDisabled()||!state.teamRole;$('readbackBtn').classList.toggle('hidden',!state.pendingReadback);$('readbackBtn').disabled=clinicalDisabled();$('teamLog').innerHTML=p.teamMessages.length?p.teamMessages.slice().reverse().map(m=>`<div class="feed-item"><small>${fmtTime(m.time)} · ${esc(m.role)}</small><div>${esc(m.message)}</div><div>${m.readback?'Read-back confirmed':'Read-back not confirmed'}</div></div>`).join(''):'<p class="muted">No team communication recorded.</p>';}
function renderResults(){const p=state.patients[state.selectedId];let html=p.results.length?p.results.map(r=>`<div class="feed-item ${esc(r.tone)}"><small>${fmtTime(r.availableAt)}</small><b>${esc(r.title)}</b>${r.reviewedAt==null?'<div class="muted">Result not yet opened.</div>':`<div>${esc(r.text)}</div>`}<div class="row">${r.reviewedAt==null?`<button data-review="${r.id}" ${clinicalDisabled()?'disabled':''}>Review · 0:10</button>`:''}${r.reviewedAt!=null&&r.requiresInterpretation&&r.interpretedAt==null?`<button data-interpret="${r.id}" ${clinicalDisabled()?'disabled':''}>Interpret · 0:15</button>`:''}${r.interpretedAt!=null?'<span class="badge">Interpreted</span>':''}</div></div>`).join(''):'<p class="muted">No results available.</p>';if(state.selectedId==='nora'&&state.flags.noraJudgmentPrompt&&!state.noraJudgment)html+=`<div class="feed-item warn"><b>Commit a provisional culture interpretation</b><select id="noraJudgment"><option value="likely pathogen">Likely pathogen</option><option value="indeterminate">Indeterminate</option><option value="likely contaminant">Likely contaminant</option></select><label>Confidence <span id="noraConfidenceLabel">50%</span></label><input id="noraConfidence" type="range" min="0" max="100" value="50"><button id="submitNoraJudgment" class="primary" ${clinicalDisabled()?'disabled':''}>Commit judgment · 0:20</button></div>`;if(state.noraJudgment&&state.selectedId==='nora')html+=`<div class="feed-item"><b>Provisional judgment recorded</b><div>${esc(state.noraJudgment.value)} at ${state.noraJudgment.confidence}% confidence</div></div>`;$('resultLog').innerHTML=html;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewResult(state.selectedId,b.dataset.review));document.querySelectorAll('[data-interpret]').forEach(b=>b.onclick=()=>interpretResult(state.selectedId,b.dataset.interpret));if($('noraConfidence'))$('noraConfidence').oninput=e=>$('noraConfidenceLabel').textContent=`${e.target.value}%`;if($('submitNoraJudgment'))$('submitNoraJudgment').onclick=()=>submitNoraJudgment($('noraJudgment').value,$('noraConfidence').value);}
function renderPages(){const pages=state.pages.slice().reverse();$('openPageCount').textContent=`${state.pages.filter(p=>p.resolvedAt==null).length} open`;$('pages').innerHTML=pages.length?pages.map(p=>`<div class="feed-item ${p.urgent?'bad':''}"><small>${fmtTime(p.createdAt)} · ${esc(state.patients[p.patientId].name)}</small><b>${esc(p.title)}</b><div>${esc(p.text)}</div><div class="row">${p.ackAt==null?`<button data-ack="${p.id}" ${clinicalDisabled()?'disabled':''}>Acknowledge · 0:10</button>`:`<span class="badge">Ack ${fmtTime(p.ackAt-p.createdAt)}</span>`}${p.responseAt!=null?`<span class="badge">Response ${fmtTime(p.responseAt-p.createdAt)}</span>`:''}${p.resolvedAt!=null?'<span class="badge">Resolved</span>':''}</div></div>`).join(''):'<p class="muted">No pages yet.</p>';document.querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>acknowledgePage(b.dataset.ack));}
function renderLedger(){$('attentionTotal').textContent=fmtTime(state.totalAttention);$('ledger').innerHTML=state.ledger.length?state.ledger.slice(-12).reverse().map(x=>`<div class="feed-item"><small>${fmtTime(x.start)}–${fmtTime(x.end)}</small><b>${esc(x.label)}</b><div>${x.pausedPractice?'Practice pause — unscored':'Attention '+fmtTime(x.seconds)}</div></div>`).join(''):'<p class="muted">No learner attention spent.</p>';}
function renderAttemptHistory(){$('attemptHistory').innerHTML=learnerRecord.attempts.length?learnerRecord.attempts.slice().reverse().map(a=>`<div class="feed-item ${a.mastery?'good':''}"><small>${new Date(a.completedAt).toLocaleString()}</small><b>Attempt ${esc(a.variantId)} · ${a.overallScore}%</b><div>${a.mastery?'Formative mastery standard met':'Remediation assigned'} · ${esc(a.mode)}</div></div>`).join(''):'<p class="muted">No completed attempts on this device.</p>';}
function renderEndModal(){$('endModal').classList.remove('hidden');if($('cancelEndBtn'))$('cancelEndBtn').classList.toggle('hidden',!!state.flags.handoffForced);$('finalRanking').innerHTML=state.patientOrder.map(id=>rankingControl('final',id)).join('');$('handoffForms').innerHTML=state.patientOrder.map(id=>{const p=state.patients[id];return`<div class="handoff-patient"><h3>${esc(p.name)}</h3>${handoffField(id,'illness','Illness severity')}${handoffField(id,'summary','Patient summary')}${handoffField(id,'actions','Action list')}${handoffField(id,'pending','Pending work and owner')}${handoffField(id,'contingency','Situation awareness and contingency')}</div>`;}).join('');$('endError').textContent='';}
function handoffField(id,key,label){return`<label for="handoff-${id}-${key}">${label}</label><textarea id="handoff-${id}-${key}" rows="2"></textarea>`;}
function readHandoffs(){const out={};for(const id of state.patientOrder){out[id]={};for(const key of['illness','summary','actions','pending','contingency'])out[id][key]=$(`handoff-${id}-${key}`).value.trim();}return out;}
