'use strict';
function renderDebrief(){if(!state.score)return;const s=state.score,a=state.analytics;$('debriefOutcome').textContent=state.endReason;$('masteryBadge').textContent=state.mode==='practice'?'Practice run — not comparable':s.mastery?'Formative mastery standard met':'Mastery standard not met';$('masteryBadge').className=`mastery ${s.mastery?'met':''}`;
$('objectiveDebrief').innerHTML=`<h3>Objective-linked performance</h3><div class="score-grid"><div class="score-card"><b>Overall</b><span>${s.overall}%</span></div>${state.caseData.objectives.map(o=>`<div class="score-card"><b>${esc(o.id)} · ${esc(o.label)}</b><span>${s.objectiveScores[o.id]}%</span><small>${esc(o.framework?.[0]?.claimBoundary||'Formative mapping only.')}</small></div>`).join('')}</div>`;
$('analyticsDebrief').innerHTML=`<h3>Diagnostic-process analytics</h3>${analyticsNarrative(a).map(x=>`<div class="score-card"><b>${esc(x.label)}</b><span>${esc(x.value)}</span><p>${esc(x.interpretation)}</p></div>`).join('')}`;
const misses=s.results.filter(r=>!r.met),strengths=s.results.filter(r=>r.met);$('missesDebrief').innerHTML=`<h3>Specific feedback</h3><h4>Missed or incomplete</h4>${misses.length?misses.map(m=>`<div class="miss"><b>${esc(m.label)}</b><p>${esc(m.rationale)}</p><p><strong>Observed consequence:</strong> ${esc(m.consequence)}</p></div>`).join(''):'<p>No rubric omissions.</p>'}<h4>Demonstrated</h4>${strengths.map(x=>`<div class="strength">${esc(x.label)}</div>`).join('')}`;
const reasons=state.patients.maya.reasoning;$('reasoningDebrief').innerHTML=`<h3>Reasoning replay</h3><div class="score-grid"><div class="score-card"><b>Learner commitments</b>${reasons.length?reasons.map(r=>`<p>${fmtTime(r.time)} — ${esc(r.diagnosis)} (${r.confidence}%)<br>${esc(r.problem)}</p>`).join(''):'<p>None recorded.</p>'}</div><div class="score-card"><b>Expert problem representation</b><p>Six-day-old term infant with progressive poor feeding, tachypnea, oliguria, upper–lower extremity perfusion disparity, weak femoral pulses, hepatomegaly, and rising lactate: shock from ductal-dependent systemic circulation until proven otherwise, while sepsis and metabolic threats are covered in parallel.</p></div></div>`;
$('handoffDebrief').innerHTML=`<h3>I-PASS handoff</h3><p>Structured-field completeness: <b>${Math.round(handoffCompleteness()*100)}%</b>. Pending ownership: <b>${pendingOwnershipComplete()?'complete':'incomplete'}</b>.</p>`;
const weakest=Object.entries(s.objectiveScores).sort((x,y)=>x[1]-y[1])[0]?.[0],rem=state.caseData.remediation.find(r=>r.objectiveId===weakest);$('remediationDebrief').innerHTML=`<h3>Assigned remediation and next attempt</h3><div class="miss"><b>${esc(rem?.title||'Targeted remediation')}</b><p>${esc(rem?.instruction||'Review the missed objective and repeat the case.')}</p><p>Assigned variant: <b>${esc(state.nextVariantId)}</b></p></div>`;
$('timelineDebrief').innerHTML=`<h3>Timeline replay</h3>${state.timeline.slice().sort((x,y)=>x.time-y.time).map(e=>`<div class="feed-item"><small>${fmtTime(e.time)}${e.patientId?` · ${esc(state.patients[e.patientId].name)}`:''}</small><div>${esc(e.text)}</div></div>`).join('')}`;}
