// Drives the Pediatric Hospital Simulator through its real engine and DOM.
import { watchForErrors } from './harness.mjs';

export const CORRECT_RANKING = { maya: '1', eli: '2', nora: '3', jamal: '4' };

export function fullHandoffs() {
  return {
    maya: { illness:'Critical watcher after neonatal shock stabilization.', summary:'Neonate with shock, weak femoral pulses, and ductal-dependent systemic perfusion.', actions:'Prostaglandin, monitoring, cultures, antibiotics, cardiology escalation, respiratory readiness, and reassessment completed.', pending:'Incoming resident owns pending echo results, open pages, and repeat perfusion reassessment.', contingency:'If perfusion worsens, apnea occurs, or lactate rises, provide ventilatory support and call cardiology and the attending immediately.' },
    eli: { illness:'Watcher for hypoxemic respiratory deterioration.', summary:'Infant with bronchiolitis, increased work of breathing, and oxygen requirement.', actions:'Respiratory exam, suction, low-flow oxygen, hydration assessment, and respiratory reassessment completed.', pending:'Incoming resident and nurse own monitoring, open-page review, pending results, and repeat respiratory reassessment.', contingency:'If breathing worsens or desaturation recurs despite supportive care, reassess and escalate respiratory support.' },
    nora: { illness:'Watcher with invasive bacterial infection risk.', summary:'Young infant with fever, abnormal inflammatory markers, and positive culture requiring bacteremia and meningitis evaluation.', actions:'Culture review, inflammatory markers, antibiotics, CSF evaluation, and admission planning completed.', pending:'Incoming resident owns pending culture speciation, CSF results, open pages, and antibiotic reassessment.', contingency:'If fever, perfusion, or mental status worsens, call the attending and escalate sepsis care.' },
    jamal: { illness:'Stable low-risk chest pain patient.', summary:'Adolescent with reproducible musculoskeletal chest pain and no current high-risk features.', actions:'Chest-wall exam, analgesia, risk explanation, and caregiver update completed.', pending:'Incoming resident owns review of any pending result or page and reassesses symptoms before discharge.', contingency:'If exertional pain, syncope, dyspnea, or worsening symptoms occur, reassess and escalate.' },
  };
}

export async function runScenario(browser, origin, { plan='', ranking=CORRECT_RANKING, completeShift:doComplete=true, mode='assessment' }={}) {
  const context=await browser.newContext({viewport:{width:1440,height:1000}}), page=await context.newPage(), errors=watchForErrors(page);
  await page.goto(`${origin}/phs/`); await page.evaluate(()=>localStorage.clear()); await page.reload();
  await page.waitForFunction(()=>state?.caseData,{timeout:15000});
  await page.evaluate(({ranking,mode})=>{for(const [pid,rank] of Object.entries(ranking))document.getElementById(`initial-rank-${pid}`).value=rank;document.querySelector(`input[name=mode][value=${mode}]`).checked=true;document.getElementById('startBtn').click();state.running=false;},{ranking,mode});
  const result=await page.evaluate(({planSrc,doComplete,handoffs})=>{state.running=true;eval(planSrc);const beforeHandoff={time:state.time,ended:state.ended,endReason:state.endReason,handoffForced:!!state.flags.handoffForced,handoffWarned:!!state.flags.handoffWarned};if(doComplete&&!state.ended)completeShift({maya:1,eli:2,nora:3,jamal:4},handoffs);const score=state.score;return{beforeHandoff,ended:state.ended,endReason:state.endReason,time:state.time,maya:{vitals:JSON.parse(JSON.stringify(state.patients.maya.vitals)),flags:JSON.parse(JSON.stringify(state.patients.maya.flags))},overall:score?.overall??null,objectives:score?.objectiveScores??null,mastery:score?.mastery??null,criticalFailure:score?.criticalFailure??null,metItems:score?score.results.filter(r=>r.met).map(r=>r.id):[],missedItems:score?score.results.filter(r=>!r.met).map(r=>r.id):[],masteryBadge:document.getElementById('masteryBadge').innerText,urgentPages:state.pages.filter(p=>p.urgent).map(p=>({title:p.title,createdAt:p.createdAt,responseAt:p.responseAt}))};},{planSrc:plan,doComplete,handoffs:fullHandoffs()});
  result.errors=[...new Set(errors)];await context.close();return result;
}

export async function readVitalTiles(page){return page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('#vitals .vital')].map(tile=>[tile.querySelector('small').textContent.trim(),tile.querySelector('strong').textContent.trim()])));}

export const PLAN_DO_NOTHING=`while(state.time<950&&!state.ended)advanceScenario(30,true);`;
export const PLAN_NOVICE_BOLUS=`selectPatient('maya');commitReasoning({problem:'Neonatal sepsis',diagnosis:'Neonatal sepsis',alternatives:'none',plan:'fluids and antibiotics',confidence:85});placeOrder('bigbolus');placeOrder('antibiotics');while(state.time<950&&!state.ended)advanceScenario(30,true);`;
export const PLAN_PGE_NO_AIRWAY=`state.flags.forcePgeApnea=true;selectPatient('maya');performExam('fourbp');commitReasoning({problem:'Neonatal shock',diagnosis:'Ductal-dependent systemic circulation / critical coarctation',alternatives:'Sepsis',plan:'PGE1',confidence:80});placeOrder('pge');while(state.time<950&&!state.ended)advanceScenario(30,true);`;
export const PLAN_PGE_RESCUED=`state.flags.forcePgeApnea=true;selectPatient('maya');performExam('fourbp');commitReasoning({problem:'Neonatal shock',diagnosis:'Ductal-dependent systemic circulation / critical coarctation',alternatives:'Sepsis',plan:'PGE1 with airway ready and PPV if apnea',confidence:80});placeOrder('airway');placeOrder('pge');while(!state.patients.maya.flags.pgeApnea&&!state.ended)advanceScenario(5,true);if(state.patients.maya.flags.pgeApnea){placeOrder('ventilation');advanceScenario(10,true);}for(let i=0;i<8&&!state.ended;i++)advanceScenario(30,true);`;

export const PLAN_EXPERT=`
selectPatient('maya');askHistory('How has she been feeding and urinating?','parent');
commitReasoning({problem:'Neonatal shock with differential perfusion from ductal closure',diagnosis:'Ductal-dependent systemic circulation / critical coarctation',alternatives:'Sepsis and metabolic disease; pulse and pressure gradients sought',plan:'Immediate PGE1 with monitored access, airway readiness, urgent cardiology, and parallel sepsis coverage',confidence:80});
placeOrder('airway');placeOrder('pge');placeOrder('glucose');placeOrder('culture');placeOrder('antibiotics');
sendTeamMessage('cardiology','Urgent unstable neonate with shock and ductal-dependent coarctation physiology. PGE is running with monitored access and airway equipment ready. Please evaluate now for echo and CICU transfer; notify me of deterioration.');confirmReadback();placeOrder('echo');
sendTeamMessage('parent','Your baby is critically ill from a heart circulation problem. We started medicine to improve blood flow, are prepared to support breathing, and the cardiac team is evaluating her now.');performExam('pulses');repeatVitals();
for(const page of state.pages.filter(item=>item.urgent&&item.responseAt==null)){acknowledgePage(page.id);repeatVitals();}
selectPatient('nora');performExam('appearance');placeOrder('reviewculture');advanceScenario(10,true);for(const result of state.patients.nora.results)if(result.reviewedAt==null)reviewResult('nora',result.id);if(state.flags.noraJudgmentPrompt)submitNoraJudgment('likely pathogen',80);
commitReasoning({problem:'Febrile young infant with likely invasive bacterial infection',diagnosis:'Febrile young infant with invasive bacterial infection',alternatives:'Contaminant less likely given time to positivity and organism',plan:'Inflammatory markers, parenteral antibiotics, CSF studies, admission, and culture ownership',confidence:85});placeOrder('inflammatory');placeOrder('antibiotics');
selectPatient('maya');while(!state.patients.maya.results.some(result=>result.orderId==='echo')&&!state.flags.handoffForced)advanceScenario(15,true);for(const result of state.patients.maya.results){if(result.reviewedAt==null)reviewResult('maya',result.id);if(result.reviewedAt!=null&&result.requiresInterpretation&&result.interpretedAt==null)interpretResult('maya',result.id,phsDefaultInterpretation('maya',result));}repeatVitals();
selectPatient('nora');placeOrder('lp');placeOrder('admit');
selectPatient('eli');performExam('respiratory');placeOrder('suction');placeOrder('oxygen');selectPatient('jamal');performExam('chestwall');placeOrder('analgesia');placeOrder('family');advanceScenario(10,true);
for(let i=0;i<8&&!state.flags.handoffForced&&!state.ended;i++){advanceScenario(30,true);for(const page of state.pages.filter(item=>item.urgent&&item.responseAt==null)){acknowledgePage(page.id);repeatVitals();}for(const pid of ['maya','nora','eli','jamal']){const prior=state.selectedId;selectPatient(pid);for(const result of state.patients[pid].results){if(result.reviewedAt==null)reviewResult(pid,result.id);if(result.reviewedAt!=null&&result.requiresInterpretation&&result.interpretedAt==null)interpretResult(pid,result.id,phsDefaultInterpretation(pid,result));}selectPatient(prior);}}
`;

export const PLAN_STABILISE_MAYA=`selectPatient('maya');performExam('fourbp');commitReasoning({problem:'Neonatal shock',diagnosis:'Ductal-dependent systemic circulation / critical coarctation',alternatives:'Sepsis',plan:'PGE1 with monitored access and airway ready',confidence:80});placeOrder('airway');placeOrder('pge');`;
