(function(){
  'use strict';
  var M=window.WordExpeditionMastery,ART=window.WordExpeditionArt,app=document.getElementById('quest-app');if(!M||!app)return;
  var learner=null,session=null;

  function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}
  function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=x[i];x[i]=x[j];x[j]=t;}return x;}
  function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function params(){return new URLSearchParams(location.search);}
  function required(word){return M.vocabDomains(word);}
  function wordScore(word){return Math.max.apply(null,required(word).map(function(domain){return M.weakness(learner,word,domain);}));}
  function rankedWords(){return M.BANK.map(function(word){return {word:word,ready:M.vocabReady(learner,word),score:wordScore(word)};}).sort(function(a,b){return (a.ready-b.ready)||b.score-a.score;});}
  function missingDomains(word){return required(word).filter(function(domain){return M.independentCorrects(learner,word,domain)<1||M.unresolved(learner,word,domain);}).sort(function(a,b){return M.weakness(learner,word,b)-M.weakness(learner,word,a);});}
  function phase(){var forced=params().get('mode');if(forced==='confidence')return 'confidence';var d=dateKey(),r=M.readiness(learner);if(d>='2026-08-31')return 'confidence';if(d==='2026-08-30'&&r.vocab>=10)return 'final';if(r.vocab===12)return 'final';return d==='2026-08-30'?'retention':'acquisition';}
  function estimateMinutes(){var items=0;M.BANK.forEach(function(w){items+=missingDomains(w).length;});var misses=M.recentErrors(learner,12).filter(function(e){return e.domain!=='spelling';}).length;return Math.max(3,Math.min(12,Math.ceil((items+Math.min(6,misses))*0.28)));}
  function bossArt(){try{return ART&&ART.monster?ART.monster('boss','ready'):'<div class="fallback-boss">🦉</div>';}catch(_){return '<div class="fallback-boss">🦉</div>';}}
  function runeGrid(){var weak=rankedWords().slice(0,3).map(function(x){return x.word;});return '<div class="rune-grid" aria-label="Vocabulary mastery runes">'+M.BANK.map(function(w){var ready=M.vocabReady(learner,w),cls=ready?'ready':weak.indexOf(w)>=0?'weak':'';return '<div class="quest-rune '+cls+'" data-word="'+w+'"><span class="rune-mark" aria-hidden="true">'+(ready?'◆':'◇')+'</span><strong>'+w+'</strong></div>';}).join('')+'</div>';}
  function weakStrip(){var weak=rankedWords().filter(function(x){return !x.ready;}).slice(0,4);if(!weak.length)return '<div class="weak-strip"><span class="weak-chip">All 12 runes recovered</span></div>';return '<div class="weak-strip">'+weak.map(function(x){var domains=missingDomains(x.word).map(function(d){return d==='definition'?'meaning':d;});return '<span class="weak-chip"><strong>'+x.word+'</strong> · '+esc(domains.join(' + ')||'verify')+'</span>';}).join('')+'</div>';}
  function pickLearner(){var q=params().get('learner');if(q==='Luke'||q==='Samantha'){learner=q;showDashboard();return;}app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">Monday mastery</p><h1>Recover all 12 Word Runes</h1><p>One button. The quest chooses the highest-value next interaction and stops drilling words that are already test-ready.</p><div class="quest-actions"><button class="quest-primary" data-learner="Luke">Luke</button><button class="quest-primary" data-learner="Samantha">Samantha</button></div></div><div class="boss-portrait">'+bossArt()+'</div></section>';app.querySelectorAll('[data-learner]').forEach(function(b){b.addEventListener('click',function(){learner=b.dataset.learner;history.replaceState(null,'',location.pathname+'?learner='+encodeURIComponent(learner));showDashboard();});});}
  function primaryCopy(p,r){if(p==='confidence')return 'Start 5-minute confidence check';if(p==='final')return r.vocab===12?'Face the Sunday Final Boss':'Face the Final Boss';if(p==='retention')return 'Start Retention Quest';return 'Start Mastery Quest';}
  function showDashboard(){session=null;var r=M.readiness(learner),p=phase(),pct=Math.round(r.vocab/12*100),weak=rankedWords().filter(function(x){return !x.ready;});var phaseCopy=p==='confidence'?'Monday is confirmation day. No new busywork: check all 12 quickly, then repair only actual misses.':p==='final'?'The runes are nearly secure. The full-bank Final Boss now tests transfer under realistic pressure.':p==='retention'?'Sunday is for delayed retrieval. Previously strong words stay mostly suppressed unless they need a retention check.':'Saturday is acquisition: identify weak clues, repair misses immediately, and revisit them after a delay.';
    app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">'+esc(learner)+' · '+r.vocab+'/12 test-ready</p><h1>'+(weak.length?weak.length+' '+(weak.length===1?'word stands':'words stand')+' between you and the castle':'All 12 runes recovered')+'</h1><p>'+phaseCopy+'</p><p class="deadline-note">Goal: vocabulary ready by Monday, August 31.</p><div class="quest-meter" aria-label="'+r.vocab+' of 12 vocabulary words ready"><span style="width:'+pct+'%"></span></div>'+runeGrid()+weakStrip()+'<div class="quest-actions"><button class="quest-primary" id="quest-start">'+primaryCopy(p,r)+'</button>'+(p==='final'&&r.vocab<12?'<button class="quest-secondary" id="repair-first">Repair weak words first</button>':'')+'<button class="quest-secondary" id="switch-hero">Switch learner</button></div><p class="quest-estimate">Estimated focused work for the next useful block: about '+estimateMinutes()+' minutes. Ready words are suppressed except for occasional retention checks.</p></div><div class="boss-portrait">'+bossArt()+'</div></section>';
    document.getElementById('switch-hero').addEventListener('click',function(){learner=null;history.replaceState(null,'',location.pathname);pickLearner();});
    document.getElementById('quest-start').addEventListener('click',function(){if(p==='confidence')startConfidence();else if(p==='final')openFinalBoss();else startQuest();});
    var repair=document.getElementById('repair-first');if(repair)repair.addEventListener('click',startQuest);
  }
  function openFinalBoss(){location.href='mock-test.html?learner='+encodeURIComponent(learner)+'&mode=vocabulary&return=mastery';}

  function candidateTasks(){var out=[];M.BANK.forEach(function(w){required(w).forEach(function(domain){var needed=M.independentCorrects(learner,w,domain)<1||M.unresolved(learner,w,domain),ready=M.vocabReady(learner,w);out.push({word:w,domain:domain,needed:needed,ready:ready,score:M.weakness(learner,w,domain)+(needed?55:0)+(ready?-130:0)});});});return out.sort(function(a,b){return b.score-a.score;});}
  function buildQuest(){var ranked=rankedWords(),boss=(ranked.find(function(x){return !x.ready;})||ranked[0]).word,bossDomains=missingDomains(boss);if(!bossDomains.length)bossDomains=required(boss).slice().sort(function(a,b){return M.weakness(learner,boss,b)-M.weakness(learner,boss,a);});var tasks=[],used={};function add(t,flag){if(!t)return;var key=t.word+'|'+t.domain+'|'+(flag||'');if(used[key])return;used[key]=1;tasks.push({word:t.word,domain:t.domain,boss:t.word===boss,retry:false});}
    add({word:boss,domain:bossDomains[0]},'boss1');var candidates=candidateTasks().filter(function(t){return t.word!==boss&&t.needed;});add(candidates[0]);add(candidates[1]);if(bossDomains[1])add({word:boss,domain:bossDomains[1]},'boss2');add(candidates[2]);add(candidates[3]);if(bossDomains[2])add({word:boss,domain:bossDomains[2]},'boss3');
    var bossHadMiss=required(boss).some(function(d){var ev=M.recentEvents(learner,boss,d);return ev.some(function(e){return !e.correct&&!e.assisted;});});if(bossHadMiss)add({word:boss,domain:bossDomains[0]},'delayed');
    var all=candidateTasks();for(var i=0;tasks.length<8&&i<all.length;i++)if(!tasks.some(function(t){return t.word===all[i].word&&t.domain===all[i].domain;}))add(all[i]);
    // Mastered-word suppression: at most one already-ready retention check per eight-item quest.
    if(tasks.length<8){var retention=all.find(function(t){return t.ready&&!tasks.some(function(x){return x.word===t.word;});});if(retention)add(retention,'retention');}
    return {boss:boss,tasks:tasks.slice(0,8)};
  }
  function clue(task,seed){var d=M.DATA[task.word],list,label;if(task.domain==='definition'){list=d.definitions;label='Teacher definition';}else if(task.domain==='synonym'){list=d.syn;label='Teacher synonym';}else{list=d.ant;label='Teacher antonym';}return {text:list[(seed||0)%list.length],label:label};}
  function startQuest(){var built=buildQuest();session={kind:'quest',boss:built.boss,tasks:built.tasks,index:0,firstTry:0,resolved:0,start:Date.now(),queue:[],seed:Math.floor(Math.random()*17)};renderQuestTask();}
  function insertDelayed(task){var due=Math.min(session.index+4,session.tasks.length);if(!session.tasks.slice(session.index+1).some(function(t){return t.word===task.word&&t.domain===task.domain&&t.retry;}))session.tasks.splice(due,0,{word:task.word,domain:task.domain,boss:true,retry:true});}
  function shieldHTML(){var total=session.tasks.length;return '<div class="boss-shield" aria-label="'+session.resolved+' of '+total+' boss shield segments broken">'+Array.from({length:total},function(_,i){return '<span class="'+(i<session.resolved?'hit':'')+'"></span>';}).join('')+'</div>';}
  function renderQuestTask(){if(session.index>=session.tasks.length)return finishQuest();var task=session.tasks[session.index],c=clue(task,session.seed+session.index),choices=shuffle(M.BANK);app.innerHTML='<section class="quest-panel quest-card" id="quest-card"><span class="fun-hit" aria-hidden="true">✦ CRITICAL</span><div class="boss-hud"><div class="boss-title"><span class="question-label">'+(task.boss?'Weak-word boss':'Trail challenge')+'</span><strong>'+esc(session.boss)+' shield</strong></div>'+shieldHTML()+'</div><div class="quest-progress"><span>Challenge '+(session.index+1)+' / '+session.tasks.length+'</span><span>'+esc(c.label)+'</span></div><div class="quest-question">'+(task.domain==='definition'?'Which vocabulary word means “'+esc(c.text)+'”?':task.domain==='synonym'?'Which vocabulary word has the same meaning as “'+esc(c.text)+'”?':'Which vocabulary word has the opposite meaning of “'+esc(c.text)+'”?')+'</div><div class="quest-bank">'+choices.map(function(w){return '<button class="quest-choice" data-answer="'+w+'" type="button">'+w+'</button>';}).join('')+'</div><div class="quest-feedback" id="quest-feedback"></div></section>';
    app.querySelectorAll('[data-answer]').forEach(function(b){b.addEventListener('click',function(){answerQuest(task,b.dataset.answer);});});
  }
  function lockChoices(){app.querySelectorAll('[data-answer]').forEach(function(b){b.disabled=true;});}
  function answerQuest(task,given){lockChoices();var ok=given===task.word,card=document.getElementById('quest-card'),feedback=document.getElementById('quest-feedback');M.recordEvidence(learner,task.word,task.domain,ok,{independent:true,type:'mastery-quest-bank',error:ok?null:'word-bank discrimination'});if(ok){session.firstTry++;session.resolved++;card.dataset.state='hit';feedback.innerHTML='<div class="feedback-hit"><strong>Critical hit.</strong> '+esc(task.word)+'</div>';setTimeout(function(){session.index++;renderQuestTask();},430);return;}
    card.dataset.state='miss';insertDelayed(task);feedback.innerHTML='<div class="feedback-miss"><strong>Shield held.</strong> The answer is <strong>'+esc(task.word)+'</strong>. Look once; it disappears next.</div>';
    setTimeout(function(){feedback.innerHTML='<div class="repair-box"><strong>Rebuild from memory.</strong><form id="repair-form"><div class="repair-row"><input id="repair-word" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Type the vocabulary word from memory"><button class="repair-submit" type="submit">Break shield</button></div></form><p class="repair-note" id="repair-note">This repair does not count as mastery. The clue returns after other words.</p></div>';var input=document.getElementById('repair-word');input.focus();document.getElementById('repair-form').addEventListener('submit',function(e){e.preventDefault();if(input.value.trim().toLowerCase()!==task.word){document.getElementById('repair-note').textContent='Not yet. Reconstruct the exact vocabulary word.';input.select();return;}M.recordEvidence(learner,task.word,task.domain,true,{assisted:true,independent:false,type:'mastery-quest-repair'});session.resolved++;card.dataset.state='hit';setTimeout(function(){session.index++;renderQuestTask();},300);});},850);
  }
  function finishQuest(){M.addPracticeMs(learner,Date.now()-session.start);if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);var r=M.readiness(learner),remaining=12-r.vocab;app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Quest complete</p><div class="summary-score">'+r.vocab+'/12</div><h1>'+(remaining?remaining+' '+(remaining===1?'rune remains':'runes remain'):'All 12 runes recovered')+'</h1><p>'+session.firstTry+' of '+session.tasks.length+' challenges cleared on the first attempt. Misses were repaired, hidden, and scheduled for delayed retrieval instead of being counted as mastery.</p>'+runeGrid()+(remaining?'<div class="quest-actions"><button class="quest-primary" id="quest-again">Continue only what still needs work</button><button class="quest-secondary" id="quest-home">Mission screen</button></div>':'<div class="final-boss-callout"><strong>Final Boss unlocked.</strong><p>Now verify transfer with the full 12-word bank and the teacher-sheet relationship section.</p><div class="quest-actions"><button class="quest-primary" id="final-boss">Face Final Boss</button><button class="quest-secondary" id="quest-home">Mission screen</button></div></div>')+'</section>';
    var again=document.getElementById('quest-again');if(again)again.addEventListener('click',startQuest);document.getElementById('quest-home').addEventListener('click',showDashboard);var final=document.getElementById('final-boss');if(final)final.addEventListener('click',openFinalBoss);
  }

  function startConfidence(){var tasks=shuffle(M.BANK).map(function(word,i){var domains=required(word),domain=domains[i%domains.length];return {word:word,domain:domain,clue:clue({word:word,domain:domain},i+3)};});session={kind:'confidence',tasks:tasks,index:0,answers:[],start:Date.now()};renderConfidence();}
  function renderConfidence(){if(session.index>=session.tasks.length)return gradeConfidence();var t=session.tasks[session.index],question=t.domain==='definition'?'Which vocabulary word means “'+esc(t.clue.text)+'”?':t.domain==='synonym'?'Which vocabulary word has the same meaning as “'+esc(t.clue.text)+'”?':'Which vocabulary word has the opposite meaning of “'+esc(t.clue.text)+'”?';app.innerHTML='<section class="quest-panel quest-card"><p class="eyebrow">Monday confidence check · '+(session.index+1)+'/12</p><h1>No coaching until the end</h1><div class="quest-question">'+question+'</div><div class="quest-bank">'+shuffle(M.BANK).map(function(w){return '<button class="quest-choice" data-confidence="'+w+'" type="button">'+w+'</button>';}).join('')+'</div><p class="quest-estimate">Choose once and move on. This is confirmation, not another lesson.</p></section>';app.querySelectorAll('[data-confidence]').forEach(function(b){b.addEventListener('click',function(){session.answers.push(b.dataset.confidence);session.index++;renderConfidence();});});}
  function gradeConfidence(){var correct=0,misses=[];session.tasks.forEach(function(t,i){var ok=session.answers[i]===t.word;if(ok)correct++;else misses.push(t.word);M.recordEvidence(learner,t.word,t.domain,ok,{independent:true,type:'monday-confidence',error:ok?null:'confidence-check miss'});});M.addPracticeMs(learner,Date.now()-session.start);if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Monday confidence check</p><div class="summary-score">'+correct+'/12</div><h1>'+(correct===12?'Locked in. Stop studying.':'Repair only the misses.')+'</h1><p>'+(correct===12?'All 12 survived a mixed, no-feedback pass. More practice now has low value.':'Do not rerun the whole list. The Mastery Quest will prioritize '+esc(Array.from(new Set(misses)).join(', '))+'.')+'</p>'+runeGrid()+'<div class="quest-actions">'+(correct<12?'<button class="quest-primary" id="repair-misses">Repair misses</button>':'')+'<button class="quest-secondary" id="confidence-home">Mission screen</button></div></section>';var repair=document.getElementById('repair-misses');if(repair)repair.addEventListener('click',startQuest);document.getElementById('confidence-home').addEventListener('click',showDashboard);}

  window.addEventListener('wordexpedition:mastery-updated',function(){if(!session&&learner)showDashboard();});pickLearner();
})();
