(function(){
  'use strict';
  var M=window.WordExpeditionMastery,S=window.WordExpeditionSpelling,ART=window.WordExpeditionArt,app=document.getElementById('quest-app');if(!M||!S||!app)return;
  var learner=null,session=null;

  function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}
  function params(){return new URLSearchParams(location.search);}
  function bossArt(){try{return ART&&ART.monster?ART.monster('boss','ready'):'<div class="fallback-boss">🦉</div>';}catch(_){return '<div class="fallback-boss">🦉</div>';}}
  function cloud(){if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);}

  function spellingDots(){var r=M.readiness(learner);return '<div class="rune-grid" aria-label="'+r.spelling+' of 12 spelling words ready">'+M.BANK.map(function(_,i){return '<div class="quest-rune '+(i<r.spelling?'ready':'')+'"><span class="rune-mark" aria-hidden="true">'+(i<r.spelling?'◆':'◇')+'</span><strong>Word '+(i+1)+'</strong></div>';}).join('')+'</div>';}
  function spellingProgress(){var mastered=0,secondDay=0;M.BANK.forEach(function(word){var st=M.getStat(learner,word,'spelling'),days=(st.correctDays||[]).length;if(M.spellingReady(learner,word))mastered++;else if(days===1&&!M.unresolved(learner,word,'spelling'))secondDay++;});return {mastered:mastered,secondDay:secondDay};}
  function masteryMessage(score){var p=spellingProgress();if(p.mastered===12)return 'Mastery confirmed: all 12 words have clean independent spelling evidence on two different days.';if(score===12&&p.secondDay>0)return 'Perfect today. '+p.secondDay+' '+(p.secondDay===1?'word needs':'words need')+' one more clean spelling check on a different day before mastery is confirmed.';return 'Today’s quiz score and mastery are different on purpose: a word becomes spelling-ready after clean independent spelling on two different days, with no later unresolved miss.';}

  function pickLearner(){var q=params().get('learner');if(q==='Luke'||q==='Samantha'){learner=q;showDashboard();return;}app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">Spelling quest</p><h1>Who is spelling today?</h1><p>Vocabulary is complete. Now the same 12 words move to audio dictation.</p><div class="quest-actions"><button class="quest-primary" data-learner="Luke">Luke</button><button class="quest-primary" data-learner="Samantha">Samantha</button></div></div><div class="boss-portrait">'+bossArt()+'</div></section>';app.querySelectorAll('[data-learner]').forEach(function(b){b.addEventListener('click',function(){learner=b.dataset.learner;history.replaceState(null,'',location.pathname+'?learner='+encodeURIComponent(learner));showDashboard();});});}

  function showDashboard(){session=null;var r=M.readiness(learner),pct=Math.round(r.spelling/12*100);app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">'+esc(learner)+' · spelling</p><h1>12-word spelling quiz</h1><p>Listen to each word and type exactly what you hear. The spellings stay hidden until all 12 answers are finished.</p><p class="quest-estimate"><strong>How mastery works:</strong> one perfect quiz is a strong result, but a word turns “ready” only after clean independent spelling on two different days.</p><div class="quest-meter" aria-label="'+r.spelling+' of 12 spelling words ready"><span style="width:'+pct+'%"></span></div>'+spellingDots()+'<div class="quest-actions"><button class="quest-primary" id="quest-start">Start spelling quiz</button><button class="quest-secondary" id="switch-hero">Switch learner</button></div><p class="quest-estimate">Vocabulary progress is preserved. Spelling evidence is recorded separately.</p></div><div class="boss-portrait">'+bossArt()+'</div></section>';document.getElementById('quest-start').addEventListener('click',startQuiz);document.getElementById('switch-hero').addEventListener('click',function(){learner=null;history.replaceState(null,'',location.pathname);pickLearner();});}

  function startQuiz(){session={kind:'quiz',order:S.shuffle(M.BANK),index:0,answers:[],start:Date.now()};renderQuiz();speakCurrent();}

  function renderQuiz(){var s=session;if(s.index>=s.order.length){gradeQuiz();return;}app.innerHTML='<section class="quest-panel quest-card"><div class="quest-progress"><span>Spelling '+(s.index+1)+' / 12</span><span>No answers until the end</span></div><p class="eyebrow">Audio dictation</p><h1>Listen. Type the word.</h1><p id="audio-status">You can replay the word as many times as you need.</p><button type="button" class="quest-secondary" id="hear-word">Hear word again</button><form id="spelling-form"><div class="repair-row"><input id="spelling-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="next" aria-label="Type the spelling"><button class="repair-submit" type="submit">'+(s.index===11?'Finish quiz':'Next word')+'</button></div></form></section>';document.getElementById('hear-word').addEventListener('click',speakCurrent);document.getElementById('spelling-form').addEventListener('submit',function(e){e.preventDefault();var input=document.getElementById('spelling-answer'),value=input.value.trim();if(!value){input.focus();return;}s.answers.push(value);s.index++;if(s.index>=12)gradeQuiz();else{renderQuiz();speakCurrent();}});document.getElementById('spelling-answer').focus();}

  function speakCurrent(){if(!session||session.kind!=='quiz'||session.index>=12)return;S.speak(session.order[session.index],document.getElementById('audio-status'));}

  function gradeQuiz(){var s=session,graded=S.grade(s.order,s.answers,M.spellingError);graded.items.forEach(function(item){M.recordEvidence(learner,item.word,'spelling',item.correct,{independent:true,type:'mastery-spelling-quiz',error:item.error});});M.addPracticeMs(learner,Date.now()-s.start);cloud();session={kind:'results',correct:graded.correct,misses:graded.misses,repairIndex:0};renderResults();}

  function renderResults(){var s=session;app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Spelling quiz complete</p><div class="summary-score">'+s.correct+'/12</div><h1>'+(s.misses.length?s.misses.length+' '+(s.misses.length===1?'word needs':'words need')+' repair':'Clean spelling quiz')+'</h1><p class="quest-estimate">'+esc(masteryMessage(s.correct))+'</p>'+(s.misses.length?'<div class="mock-review">'+s.misses.map(function(m){return '<div class="mock-review-row"><strong>'+esc(m.word)+'</strong><span>You wrote: '+esc(m.given||'blank')+'</span><span class="miss">'+esc(m.error||'spelling miss')+'</span></div>';}).join('')+'</div>':'<p>All 12 words were spelled correctly from dictation.</p>')+'<div class="quest-actions">'+(s.misses.length?'<button class="quest-primary" id="repair-misses">Repair missed words</button>':'<button class="quest-primary" id="quest-home">Done</button>')+'<button class="quest-secondary" id="quiz-again">Take another spelling quiz</button></div></section>';document.getElementById('quiz-again').addEventListener('click',startQuiz);var repair=document.getElementById('repair-misses');if(repair)repair.addEventListener('click',startRepair);var home=document.getElementById('quest-home');if(home)home.addEventListener('click',showDashboard);}

  function startRepair(){session.repairIndex=0;renderRepairTeach();}

  function renderRepairTeach(){var s=session;if(s.repairIndex>=s.misses.length){finishRepair();return;}var miss=s.misses[s.repairIndex];app.innerHTML='<section class="quest-panel quest-card"><p class="eyebrow">Repair '+(s.repairIndex+1)+' / '+s.misses.length+'</p><h1>'+esc(miss.word)+'</h1><p>Study the exact spelling once. Then hide it and rebuild it from memory.</p><button class="quest-primary" id="hide-word">Hide word</button></section>';document.getElementById('hide-word').addEventListener('click',function(){renderRepairRecall(miss);});}

  function renderRepairRecall(miss){app.innerHTML='<section class="quest-panel quest-card"><p class="eyebrow">Answer hidden</p><h1>Spell the word from memory.</h1><button type="button" class="quest-secondary" id="hear-repair">Hear word</button><form id="repair-form"><div class="repair-row"><input id="repair-word" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Type the corrected spelling"><button class="repair-submit" type="submit">Check repair</button></div></form><p class="repair-note" id="repair-note">Exact spelling required.</p></section>';document.getElementById('hear-repair').addEventListener('click',function(){S.speak(miss.word,document.getElementById('repair-note'));});var input=document.getElementById('repair-word');input.focus();document.getElementById('repair-form').addEventListener('submit',function(e){e.preventDefault();if(S.normalize(input.value)!==S.normalize(miss.word)){document.getElementById('repair-note').textContent='Not yet. Look at the word once more, then try again.';setTimeout(function(){renderRepairTeach();},650);return;}M.recordEvidence(learner,miss.word,'spelling',true,{assisted:true,independent:false,type:'mastery-spelling-repair'});session.repairIndex++;renderRepairTeach();});}

  function finishRepair(){cloud();app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Repair complete</p><h1>Missed spellings rebuilt.</h1><p>The repair is saved, but only a future independent spelling attempt counts toward mastery.</p><div class="quest-actions"><button class="quest-primary" id="quest-home">Mission screen</button><button class="quest-secondary" id="quiz-again">Take another spelling quiz</button></div></section>';document.getElementById('quest-home').addEventListener('click',showDashboard);document.getElementById('quiz-again').addEventListener('click',startQuiz);}

  pickLearner();
})();
