(function(){
  'use strict';
  var M=window.WordExpeditionMastery,ART=window.WordExpeditionArt,app=document.getElementById('quest-app');if(!M||!app)return;
  var learner=null,session=null;

  function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}
  function norm(v){return String(v||'').toLowerCase().trim();}
  function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=x[i];x[i]=x[j];x[j]=t;}return x;}
  function params(){return new URLSearchParams(location.search);}
  function bossArt(){try{return ART&&ART.monster?ART.monster('boss','ready'):'<div class="fallback-boss">🦉</div>';}catch(_){return '<div class="fallback-boss">🦉</div>';}}
  function cloud(){if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);}

  function rankedWords(){return M.BANK.map(function(word){return {word:word,ready:M.spellingReady(learner,word),score:M.weakness(learner,word,'spelling')};}).sort(function(a,b){return (a.ready-b.ready)||b.score-a.score;});}
  function spellingDots(){var r=M.readiness(learner);return '<div class="rune-grid" aria-label="'+r.spelling+' of 12 spelling words ready">'+M.BANK.map(function(_,i){return '<div class="quest-rune '+(i<r.spelling?'ready':'')+'"><span class="rune-mark" aria-hidden="true">'+(i<r.spelling?'◆':'◇')+'</span><strong>Word '+(i+1)+'</strong></div>';}).join('')+'</div>';}

  function pickLearner(){var q=params().get('learner');if(q==='Luke'||q==='Samantha'){learner=q;showDashboard();return;}app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">Spelling quest</p><h1>Who is spelling today?</h1><p>Vocabulary is complete. Now the same 12 words move to audio dictation.</p><div class="quest-actions"><button class="quest-primary" data-learner="Luke">Luke</button><button class="quest-primary" data-learner="Samantha">Samantha</button></div></div><div class="boss-portrait">'+bossArt()+'</div></section>';app.querySelectorAll('[data-learner]').forEach(function(b){b.addEventListener('click',function(){learner=b.dataset.learner;history.replaceState(null,'',location.pathname+'?learner='+encodeURIComponent(learner));showDashboard();});});}

  function showDashboard(){session=null;var r=M.readiness(learner),pct=Math.round(r.spelling/12*100);app.innerHTML='<section class="quest-panel quest-hero"><div><p class="eyebrow">'+esc(learner)+' · spelling</p><h1>12-word spelling quiz</h1><p>Listen to each word and type exactly what you hear. The spellings stay hidden until all 12 answers are finished.</p><div class="quest-meter" aria-label="'+r.spelling+' of 12 spelling words ready"><span style="width:'+pct+'%"></span></div>'+spellingDots()+'<div class="quest-actions"><button class="quest-primary" id="quest-start">Start spelling quiz</button><button class="quest-secondary" id="switch-hero">Switch learner</button></div><p class="quest-estimate">Vocabulary progress is preserved. This quiz records spelling separately.</p></div><div class="boss-portrait">'+bossArt()+'</div></section>';document.getElementById('quest-start').addEventListener('click',startQuiz);document.getElementById('switch-hero').addEventListener('click',function(){learner=null;history.replaceState(null,'',location.pathname);pickLearner();});}

  function startQuiz(){session={kind:'quiz',order:shuffle(M.BANK),index:0,answers:[],start:Date.now()};renderQuiz();setTimeout(speakCurrent,80);}

  function renderQuiz(){var s=session;if(s.index>=s.order.length){gradeQuiz();return;}app.innerHTML='<section class="quest-panel quest-card"><div class="quest-progress"><span>Spelling '+(s.index+1)+' / 12</span><span>No answers until the end</span></div><p class="eyebrow">Audio dictation</p><h1>Listen. Type the word.</h1><p id="audio-status">You can replay the word as many times as you need.</p><button type="button" class="quest-secondary" id="hear-word">Hear word again</button><form id="spelling-form"><div class="repair-row"><input id="spelling-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="next" aria-label="Type the spelling"><button class="repair-submit" type="submit">'+(s.index===11?'Finish quiz':'Next word')+'</button></div></form></section>';document.getElementById('hear-word').addEventListener('click',speakCurrent);document.getElementById('spelling-form').addEventListener('submit',function(e){e.preventDefault();var input=document.getElementById('spelling-answer'),value=input.value.trim();if(!value){input.focus();return;}s.answers.push(value);s.index++;if(s.index>=12)gradeQuiz();else{renderQuiz();setTimeout(speakCurrent,50);}});document.getElementById('spelling-answer').focus();}

  function speakCurrent(){if(!session||session.kind!=='quiz'||session.index>=12)return;var status=document.getElementById('audio-status');if(!('speechSynthesis'in window)){if(status)status.textContent='Audio is unavailable. Ask an adult to read the spelling word without showing it.';return;}try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(session.order[session.index]);u.lang='en-US';u.rate=.92;u.onerror=function(){if(status)status.textContent='Audio is unavailable. Ask an adult to read the spelling word without showing it.';};speechSynthesis.speak(u);}catch(_){if(status)status.textContent='Audio is unavailable. Ask an adult to read the spelling word without showing it.';}}

  function gradeQuiz(){var s=session,correct=0,misses=[];s.order.forEach(function(word,i){var given=s.answers[i]||'',ok=norm(given)===word;if(ok)correct++;var error=ok?null:M.spellingError(word,given);M.recordEvidence(learner,word,'spelling',ok,{independent:true,type:'mastery-spelling-quiz',error:error});if(!ok)misses.push({word:word,given:given,error:error});});M.addPracticeMs(learner,Date.now()-s.start);cloud();session={kind:'results',correct:correct,misses:misses,repairIndex:0};renderResults();}

  function renderResults(){var s=session;app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Spelling quiz complete</p><div class="summary-score">'+s.correct+'/12</div><h1>'+(s.misses.length?s.misses.length+' '+(s.misses.length===1?'word needs':'words need')+' repair':'Clean spelling quiz')+'</h1>'+(s.misses.length?'<div class="mock-review">'+s.misses.map(function(m){return '<div class="mock-review-row"><strong>'+esc(m.word)+'</strong><span>You wrote: '+esc(m.given||'blank')+'</span><span class="miss">'+esc(m.error||'spelling miss')+'</span></div>';}).join('')+'</div>':'<p>All 12 words were spelled correctly from dictation.</p>')+'<div class="quest-actions">'+(s.misses.length?'<button class="quest-primary" id="repair-misses">Repair missed words</button>':'<button class="quest-primary" id="quest-home">Done</button>')+'<button class="quest-secondary" id="quiz-again">Take another spelling quiz</button></div></section>';var again=document.getElementById('quiz-again');again.addEventListener('click',startQuiz);var repair=document.getElementById('repair-misses');if(repair)repair.addEventListener('click',startRepair);var home=document.getElementById('quest-home');if(home)home.addEventListener('click',showDashboard);}

  function startRepair(){session.repairIndex=0;renderRepairTeach();}

  function renderRepairTeach(){var s=session;if(s.repairIndex>=s.misses.length){finishRepair();return;}var miss=s.misses[s.repairIndex];app.innerHTML='<section class="quest-panel quest-card"><p class="eyebrow">Repair '+(s.repairIndex+1)+' / '+s.misses.length+'</p><h1>'+esc(miss.word)+'</h1><p>Study the exact spelling once. Then hide it and rebuild it from memory.</p><button class="quest-primary" id="hide-word">Hide word</button></section>';document.getElementById('hide-word').addEventListener('click',function(){renderRepairRecall(miss);});}

  function renderRepairRecall(miss){app.innerHTML='<section class="quest-panel quest-card"><p class="eyebrow">Answer hidden</p><h1>Spell the word from memory.</h1><button type="button" class="quest-secondary" id="hear-repair">Hear word</button><form id="repair-form"><div class="repair-row"><input id="repair-word" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Type the corrected spelling"><button class="repair-submit" type="submit">Check repair</button></div></form><p class="repair-note" id="repair-note">Exact spelling required.</p></section>';document.getElementById('hear-repair').addEventListener('click',function(){speakWord(miss.word);});var input=document.getElementById('repair-word');input.focus();document.getElementById('repair-form').addEventListener('submit',function(e){e.preventDefault();if(norm(input.value)!==miss.word){document.getElementById('repair-note').textContent='Not yet. Look at the word once more, then try again.';setTimeout(function(){renderRepairTeach();},650);return;}M.recordEvidence(learner,miss.word,'spelling',true,{assisted:true,independent:false,type:'mastery-spelling-repair'});session.repairIndex++;renderRepairTeach();});}

  function speakWord(word){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.92;speechSynthesis.speak(u);}catch(_){} }

  function finishRepair(){cloud();app.innerHTML='<section class="quest-panel quest-summary"><p class="eyebrow">Repair complete</p><h1>Missed spellings rebuilt.</h1><p>The repair is saved, but only a future independent spelling attempt counts toward mastery.</p><div class="quest-actions"><button class="quest-primary" id="quest-home">Mission screen</button><button class="quest-secondary" id="quiz-again">Take another spelling quiz</button></div></section>';document.getElementById('quest-home').addEventListener('click',showDashboard);document.getElementById('quiz-again').addEventListener('click',startQuiz);}

  pickLearner();
})();
