(function(){
  'use strict';
  var M=window.WordExpeditionMastery,S=window.WordExpeditionSpelling,app=document.getElementById('mock-app');if(!M||!S||!app)return;
  var learner=null,session=null;

  var CONTEXT_ITEMS=[
    ['temporary','A roommate you have for only a month is _____.',['continuous','temporary','fragile','solitary']],
    ['scuffle','A black eye might be the result of a _____.',['scuffle','myth','veteran','blunder']],
    ['document',"To prove your age, a birth certificate or driver's license is a _____.",['distribute','document','cancel','reject']],
    ['solitary','A person who lives alone in the woods might be described as _____.',['continuous','solitary','temporary','fragile']],
    ['myth','The idea that you will get warts from touching a frog is a _____.',['blunder','document','scuffle','myth']],
    ['blunder','If I make a serious mistake, I commit a _____.',['scuffle','document','myth','blunder']],
    ['fragile','A box containing something easily broken might be stamped “_____.”',['solitary','temporary','fragile','continuous']],
    ['distribute','A charity might _____ food to people who need it.',['reject','cancel','scuffle','distribute']],
    ['continuous','Something that goes on without stopping is _____.',['continuous','temporary','solitary','fragile']],
    ['reject','To refuse a gift is to _____ it.',['cancel','scuffle','distribute','reject']],
    ['veteran','A person with a lot of experience at something is a _____.',['blunder','myth','document','veteran']],
    ['cancel','If I call off a party, I _____ it.',['scuffle','blunder','cancel','reject']]
  ];
  var RELATION_ITEMS=[
    ['synonym','continuous','Which word means nearly the same as “constant”?',['fragile','temporary','continuous','veteran']],
    ['synonym','blunder','Which word means nearly the same as “blooper”?',['document','myth','blunder','scuffle']],
    ['synonym','solitary','Which word means nearly the same as “single”?',['temporary','fragile','solitary','veteran']],
    ['synonym','scuffle','Which word means nearly the same as “fight”?',['myth','blunder','document','scuffle']],
    ['synonym','document','Which word means nearly the same as “record”?',['veteran','document','myth','blunder']],
    ['synonym','myth','Which word means nearly the same as “ancient story”?',['document','myth','veteran','blunder']],
    ['antonym','cancel','Which word means most nearly the opposite of “renew”?',['cancel','blunder','scuffle','distribute']],
    ['antonym','reject','Which word means most nearly the opposite of “accept”?',['scuffle','reject','blunder','distribute']],
    ['antonym','veteran','Which word means most nearly the opposite of “novice”?',['temporary','fragile','continuous','veteran']],
    ['antonym','distribute','Which word means most nearly the opposite of “collect”?',['reject','document','distribute','cancel']],
    ['antonym','fragile','Which word means most nearly the opposite of “sturdy”?',['temporary','solitary','veteran','fragile']],
    ['antonym','temporary','Which word means most nearly the opposite of “permanent”?',['veteran','continuous','temporary','solitary']]
  ];
  var RELATION_EVIDENCE_TYPES={synonym:'teacher-mock-synonym',antonym:'teacher-mock-antonym'};
  var PASSAGES=[
    ['A Visit to a Museum',[
      ['temporary','temporary','Our class visited the museum on the last day of a(n) _____ exhibit of ancient Greek vases.'],
      ['fragile','fragile',"The vases were very old and _____, so we weren't allowed to touch them."],
      ['blunder','blunder','Guards kept visitors back so no one could _____ into the display cases.'],
      ['myth','myths','The pictures showed characters from legends and _____.'],
      ['veteran','veteran','One picture showed a(n) _____ warrior fighting off attackers.']]],
    ['A Famous Declaration',[
      ['reject','rejected','The writers of the Declaration of Independence _____ English rule.'],
      ['distribute','distributed','Supporters quickly printed and _____ copies throughout the colonies.'],
      ['document','document',"The original _____ is one of America's historic treasures."]]],
    ['On the Soccer Field',[
      ['continuous','continuous','Two days of _____ rain had turned the field into a sea of mud.'],
      ['scuffle','scuffle','Before the game began, a _____ broke out in the stands.'],
      ['cancel','cancel','The referee threatened to _____ the game if order was not restored.'],
      ['veteran','veterans','Popular _____ from both teams asked the fans to behave.']]]
  ];
  var PASSAGE_RECHECK={
    temporary:'The library opened a _____ exhibit that would close next month.',
    fragile:'The museum packed the _____ vase with extra padding.',
    blunder:'One careless _____ could damage the display.',
    myths:'The book contains legends and _____ from long ago.',
    veteran:'A _____ guide knew how to handle every problem.',
    rejected:'Yesterday, the committee _____ the proposal.',
    distributed:'Volunteers _____ supplies after the storm.',
    document:'The signed _____ provided proof of the agreement.',
    continuous:'The _____ buzzing did not stop all afternoon.',
    scuffle:'A brief _____ broke out near the goal.',
    cancel:'Heavy rain may force the coach to _____ practice.',
    veterans:'The team’s _____ helped the rookies prepare.'
  };

  function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}
  function norm(v){return String(v||'').toLowerCase().trim().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ').replace(/[.!?,;:]$/g,'');}
  function params(){return new URLSearchParams(location.search);}
  function cloud(){if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);}
  function spellingMasteryCopy(score){var ready=M.readiness(learner).spelling,secondDay=0;M.BANK.forEach(function(word){var st=M.getStat(learner,word,'spelling');if(!M.spellingReady(learner,word)&&(st.correctDays||[]).length===1&&!M.unresolved(learner,word,'spelling'))secondDay++;});if(ready===12)return 'Mastery confirmed across two independent days for all 12 words.';if(score===12&&secondDay)return 'Perfect today. '+secondDay+' '+(secondDay===1?'word still needs':'words still need')+' one clean check on a different day before mastery is confirmed.';return 'The mock score is today’s performance. Spelling readiness requires clean independent spelling on two different days.';}

  function pickLearner(){var q=params().get('learner');if(q==='Luke'||q==='Samantha'){learner=q;showTypes();return;}app.innerHTML='<section class="mock-panel"><p class="eyebrow">Final verification</p><h1>Who is taking the mock?</h1><div class="mock-picker"><button class="primary-button" data-learner="Luke">Luke</button><button class="primary-button" data-learner="Samantha">Samantha</button></div><p class="mock-warning">Mocks give no correctness feedback until the entire test is submitted.</p></section>';app.querySelectorAll('[data-learner]').forEach(function(b){b.addEventListener('click',function(){learner=b.dataset.learner;showTypes();});});}
  function showTypes(){var r=M.readiness(learner);app.innerHTML='<section class="mock-panel"><p class="eyebrow">'+esc(learner)+' · final verification</p><h1>Choose a mock</h1><p>Use these after practice. The mock diagnoses misses; it does not coach during the test.</p><div class="meter-grid"><div class="meter"><strong>'+r.vocab+'/12</strong><span>vocabulary ready</span></div><div class="meter"><strong>'+r.spelling+'/12</strong><span>spelling ready</span></div><div class="meter"><strong>'+r.both+'/12</strong><span>ready in both</span></div></div><p class="mock-warning">Spelling “ready” is intentionally stricter than one quiz score: each word needs clean independent spelling on two different days.</p><div class="mock-type"><button class="mock-type-card" id="start-vocab"><strong>Teacher-style exam</strong><span>Context clues · synonyms and antonyms · three passages</span></button><button class="mock-type-card" id="start-spelling"><strong>Spelling mock</strong><span>12 words from dictation · no answer shown until the end</span></button></div><button class="text-button" id="change-learner">Change learner</button></section>';document.getElementById('start-vocab').addEventListener('click',startTeacherExam);document.getElementById('start-spelling').addEventListener('click',startSpelling);document.getElementById('change-learner').addEventListener('click',function(){learner=null;history.replaceState(null,'',location.pathname);pickLearner();});}

  function startTeacherExam(){session={type:'vocabulary',stage:'context',index:0,contextAnswers:[],relationAnswers:[]};renderTeacherItem();}
  function renderTeacherItem(){var s=session,items=s.stage==='context'?CONTEXT_ITEMS:RELATION_ITEMS,item=items[s.index],section=s.stage==='context'?'A · Meaning in context':'B · Synonyms and antonyms',prompt=s.stage==='context'?item[1]:item[2],options=item[item.length-1];app.innerHTML='<section class="mock-panel"><p class="mock-progress">'+esc(learner)+' · Section '+section+' · '+(s.index+1)+' of 12</p><h1>'+esc(prompt)+'</h1><div class="mock-instructions">Choose the best answer. Your score stays hidden until all three sections are submitted.</div><div class="exam-choices">'+options.map(function(w){return '<button type="button" class="mock-type-card exam-choice" data-exam-choice="'+esc(w)+'">'+esc(w)+'</button>';}).join('')+'</div><p class="mock-warning">No answers are checked during the exam.</p></section>';app.querySelectorAll('[data-exam-choice]').forEach(function(b){b.addEventListener('click',function(){(s.stage==='context'?s.contextAnswers:s.relationAnswers).push(b.dataset.examChoice);s.index++;if(s.index<items.length){renderTeacherItem();}else if(s.stage==='context'){s.stage='relations';s.index=0;renderTeacherItem();}else{s.stage='passages';renderTeacherPassages();}});});}
  function renderTeacherPassages(){app.innerHTML='<section class="mock-panel"><p class="mock-progress">'+esc(learner)+' · Section C · Connected passages</p><h1>Use each base word once</h1><div class="mock-instructions">Type the word that fits. <strong>Change its form when grammar requires it</strong> (for example, add <em>-ed</em> or <em>-s</em>).</div><div class="mock-word-bank">'+M.BANK.map(function(w){return '<span class="mock-word">'+esc(w)+'</span>';}).join('')+'</div><form id="teacher-exam-form"><div class="exam-passages">'+PASSAGES.map(function(p){return '<section class="exam-passage"><h2>'+esc(p[0])+'</h2>'+p[1].map(function(item){return '<label class="exam-blank"><span>'+esc(item[2])+'</span><input data-passage-answer autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false"></label>';}).join('')+'</section>';}).join('')+'</div><button type="submit" class="primary-button mock-submit">Submit entire vocabulary mock</button></form><p class="mock-warning">Nothing is graded until Submit.</p></section>';document.getElementById('teacher-exam-form').addEventListener('submit',submitTeacherExam);}
  function submitTeacherExam(e){e.preventDefault();var answers=Array.from(app.querySelectorAll('[data-passage-answer]')).map(function(x){return x.value.trim();});if(answers.some(function(x){return !x;})){alert('Fill all 12 passage blanks before submitting.');return;}var context=0,relations=0,passages=0,review=[];CONTEXT_ITEMS.forEach(function(item,i){var given=session.contextAnswers[i],ok=norm(given)===item[0],d=M.DATA[item[0]];if(ok)context++;M.recordEvidence(learner,item[0],'definition',ok,{independent:true,type:'teacher-mock-context',error:ok?null:'context choice'});if(!ok)review.push({label:'Context: '+item[0],given:given,expected:item[0],word:item[0],domain:'definition',clue:item[1],explain:item[0]+' means “'+d.definitions[0]+'.”',recheck:d.definitions[1]||d.definitions[0]});});RELATION_ITEMS.forEach(function(item,i){var given=session.relationAnswers[i],ok=norm(given)===item[1],d=M.DATA[item[1]],pool=item[0]==='synonym'?d.syn:d.ant,alt=pool[pool.length>1?1:0];if(ok)relations++;M.recordEvidence(learner,item[1],item[0],ok,{independent:true,type:RELATION_EVIDENCE_TYPES[item[0]],error:ok?null:'relationship choice'});if(!ok)review.push({label:item[0]+': '+item[1],given:given,expected:item[1],word:item[1],domain:item[0],clue:item[2],explain:item[1]+' is the vocabulary word that matches this '+item[0]+'.',recheck:'Which Unit 1 word matches “'+alt+'” as an '+item[0]+' clue?'});});var flat=[];PASSAGES.forEach(function(p){p[1].forEach(function(item){flat.push(item);});});flat.forEach(function(item,i){var ok=norm(answers[i])===item[1],changed=item[0]!==item[1],why=changed?(item[1].slice(-2)==='ed'?'The action already happened, so use the -ed form.':'The sentence means more than one, so use the plural form.'):'The base word already has the form this sentence needs.';if(ok)passages++;M.recordEvidence(learner,item[0],'definition',ok,{independent:true,type:'teacher-mock-passage',error:ok?null:'passage form'});if(changed)M.recordEvidence(learner,item[0],'pos',ok,{independent:true,type:'teacher-mock-word-form',error:ok?null:'word form'});if(!ok)review.push({label:'Passage: '+item[0],given:answers[i],expected:item[1],word:item[0],domain:changed?'pos':'definition',clue:item[2],explain:'Use “'+item[1]+'.” '+why,recheck:PASSAGE_RECHECK[item[1]]});});var result={type:'vocabulary',at:new Date().toISOString(),correct:context+relations+passages,total:36,context:context,relations:relations,passages:passages};M.recordMock(learner,result);cloud();showTeacherSummary(result,review);}
  function showTeacherSummary(result,review){session.review=review;app.innerHTML='<section class="mock-summary"><p class="eyebrow">Teacher-style exam complete</p><div class="mock-score">'+result.correct+'/36</div><p>Context clues: <strong>'+result.context+'/12</strong> · Synonyms/antonyms: <strong>'+result.relations+'/12</strong> · Passages and word forms: <strong>'+result.passages+'/12</strong></p><p class="mock-warning">This 36-point exam is today’s score. Vocabulary readiness separately tracks every assigned definition, synonym, and antonym family, so an untested relationship may still need independent evidence even after a clean exam.</p>'+(review.length?'<div class="mock-review"><h2>'+review.length+' answer'+(review.length===1?' needs':'s need')+' repair</h2>'+review.map(function(r){return '<div class="mock-review-row"><strong>'+esc(r.label)+'</strong><span>You chose: '+esc(r.given||'blank')+'</span><span class="miss">Expected: '+esc(r.expected)+'</span></div>';}).join('')+'</div>':'<h2>Clean mock—nothing needs repair.</h2>')+'<div class="learner-actions">'+(review.length?'<button class="primary-button" id="start-repair">Repair every miss now</button>':'<a class="primary-button" href="test-practice.html?learner='+encodeURIComponent(learner)+'">Continue targeted practice</a>')+'<button class="text-button" id="mock-again">Choose another mock</button></div></section>';if(review.length)document.getElementById('start-repair').addEventListener('click',startRepair);document.getElementById('mock-again').addEventListener('click',showTypes);}

  function startRepair(){session.repair={teach:session.review.slice(),recheck:[],passed:0,total:session.review.length};renderRepairTeach();}
  function repairTop(r,label){return '<p class="mock-progress">'+esc(learner)+' · Miss repair · '+r.passed+' of '+r.total+' independently retrieved</p><p class="eyebrow">'+label+'</p>';}
  function renderRepairTeach(){var r=session.repair;if(!r.teach.length){renderRepairRecheck();return;}var item=r.teach.shift();r.current=item;app.innerHTML='<section class="mock-panel">'+repairTop(r,'Learn the correction')+'<h1>'+esc(item.expected)+'</h1><div class="mock-instructions"><strong>'+esc(item.explain)+'</strong><br>'+esc(item.clue)+'</div><button class="primary-button" id="hide-repair">Hide the answer and repair it</button></section>';document.getElementById('hide-repair').addEventListener('click',function(){renderRequiredCorrection(item,false);});}
  function renderRequiredCorrection(item,fromRecheck){var r=session.repair;app.innerHTML='<section class="mock-panel">'+repairTop(r,'Answer hidden · required correction')+'<h1>'+esc(item.clue)+'</h1><form id="repair-form"><div class="exam-repair-row"><input id="repair-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Correct answer"><button class="primary-button" type="submit">Repair</button></div></form><p class="mock-warning" id="repair-note">Type the exact answer from memory.</p></section>';var input=document.getElementById('repair-answer');input.focus();document.getElementById('repair-form').addEventListener('submit',function(e){e.preventDefault();if(norm(input.value)!==norm(item.expected)){document.getElementById('repair-note').innerHTML='Not yet. Study <strong>'+esc(item.expected)+'</strong>, then type it exactly.';input.value='';input.focus();return;}M.recordEvidence(learner,item.word,item.domain,true,{assisted:true,independent:false,type:'immediate-exam-repair'});r.recheck.push(item);if(fromRecheck)renderRepairRecheck();else renderRepairTeach();});}
  function renderRepairRecheck(){var r=session.repair;if(!r.recheck.length){finishRepair();return;}var item=r.recheck.shift();app.innerHTML='<section class="mock-panel">'+repairTop(r,'Different clue · answer from memory')+'<h1>'+esc(item.recheck)+'</h1><form id="recheck-form"><div class="exam-repair-row"><input id="recheck-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" aria-label="Recheck answer"><button class="primary-button" type="submit">Check</button></div></form><div id="recheck-feedback"></div></section>';var input=document.getElementById('recheck-answer');input.focus();document.getElementById('recheck-form').addEventListener('submit',function(e){e.preventDefault();var ok=norm(input.value)===norm(item.expected);M.recordEvidence(learner,item.word,item.domain,ok,{independent:true,type:'delayed-exam-recheck',error:ok?null:'repair recheck'});if(ok){r.passed++;renderRepairRecheck();return;}document.getElementById('recheck-form').remove();document.getElementById('recheck-feedback').innerHTML='<div class="mock-instructions"><strong>Correct answer: '+esc(item.expected)+'</strong><br>'+esc(item.explain)+'</div><button class="primary-button" id="repair-again">Hide it and repair again</button>';document.getElementById('repair-again').addEventListener('click',function(){renderRequiredCorrection(item,true);});});}
  function finishRepair(){cloud();var r=session.repair;app.innerHTML='<section class="mock-summary"><p class="eyebrow">Repair complete</p><div class="mock-score">'+r.passed+'/'+r.total+'</div><h1>Every missed concept was retrieved correctly.</h1><p>The corrected evidence is saved for '+esc(learner)+'.</p><div class="learner-actions"><a class="primary-button" href="test-practice.html?learner='+encodeURIComponent(learner)+'">Continue targeted practice</a><button class="text-button" id="mock-again">Choose another mock</button></div></section>';document.getElementById('mock-again').addEventListener('click',showTypes);}

  function startSpelling(){session={type:'spelling',order:S.shuffle(M.BANK),index:0,answers:[]};renderSpelling();speakCurrent();}
  function renderSpelling(){var s=session;if(s.index>=s.order.length){gradeSpelling();return;}app.innerHTML='<section class="mock-panel"><p class="mock-progress">'+esc(learner)+' · Spelling final mock · Word '+(s.index+1)+' of 12</p><div class="mock-spelling-card"><p class="eyebrow">Audio only</p><h1>Listen. Type the word.</h1><p id="audio-status">No spelling answer will be shown until all 12 are finished.</p><button type="button" class="secondary-button hear-word" id="hear-word">Hear word</button><form id="spelling-form"><label class="sr-only" for="spelling-answer">Type the spelling</label><input class="mock-spelling-input" id="spelling-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="next"><br><button type="submit" class="primary-button mock-next">'+(s.index===11?'Finish spelling mock':'Save and hear next word')+'</button></form></div></section>';document.getElementById('hear-word').addEventListener('click',speakCurrent);document.getElementById('spelling-form').addEventListener('submit',function(e){e.preventDefault();var input=document.getElementById('spelling-answer');if(!input.value.trim()){input.focus();return;}s.answers.push(input.value.trim());s.index++;if(s.index>=12)gradeSpelling();else{renderSpelling();speakCurrent();}});document.getElementById('spelling-answer').focus();}
  function speakCurrent(){if(!session||session.type!=='spelling'||session.index>=12)return;S.speak(session.order[session.index],document.getElementById('audio-status'));}
  function gradeSpelling(){var s=session,graded=S.grade(s.order,s.answers,M.spellingError);graded.items.forEach(function(item){M.recordEvidence(learner,item.word,'spelling',item.correct,{independent:true,type:'mock-spelling',error:item.error});});var result={type:'spelling',at:new Date().toISOString(),correct:graded.correct,total:12};M.recordMock(learner,result);cloud();app.innerHTML='<section class="mock-summary"><p class="eyebrow">Spelling mock complete</p><div class="mock-score">'+graded.correct+'/12</div><p class="mock-warning">'+esc(spellingMasteryCopy(graded.correct))+'</p>'+(graded.misses.length?'<div class="mock-review"><h2>Words to repair</h2>'+graded.misses.map(function(r){return '<div class="mock-review-row"><strong>'+esc(r.word)+'</strong><span>You wrote: '+esc(r.given||'blank')+'</span><span class="miss">'+esc(r.error||'spelling miss')+'</span></div>';}).join('')+'</div>':'<h2>Clean spelling mock.</h2>')+'<p class="mock-warning">The mock is diagnostic. Missed words are now higher priority in adaptive practice.</p><div class="learner-actions"><a class="primary-button" href="test-practice.html?learner='+encodeURIComponent(learner)+'">Repair missed words</a><a class="secondary-button" href="parent-readiness.html">Parent view</a><button class="text-button" id="mock-again">Choose another mock</button></div></section>';document.getElementById('mock-again').addEventListener('click',showTypes);}

  pickLearner();
})();
