(function(){
  'use strict';
  var M=window.WordExpeditionMastery,app=document.getElementById('mock-app');if(!M||!app)return;
  var learner=null,session=null;
  var FORMS=[
    {id:'ranger',text:'The [1] ranger had worked the canyon alone for years, a truly [2] job. Each morning she would [3] trail maps to hikers and warn them the rope bridge was [4]. One [5] was letting a group cross with heavy packs — the boards cracked. She had to [6] every tour for the rest of the week. A [7] went around that a bear had chewed the ropes, but she would [8] that idea flatly. She wrote a [9] describing the real cause, and the noise of the repair crew was [10] from dawn to dusk. Two chipmunks even had a [11] over a dropped nail. The new bridge, she said, was only [12] until the steel one arrived in spring.',key:['veteran','solitary','distribute','fragile','blunder','cancel','myth','reject','document','continuous','scuffle','temporary']},
    {id:'pilot',text:'The [1] pilot did not [2] the flight, even though the fog was [3] all morning. Her one small [4] was leaving the coffee on the wing. A flight attendant began to [5] pretzels while a [6] passenger read alone in row 12. Two toddlers had a tiny [7] over a plastic cup. The captain signed a [8] saying the delay was only [9]. A rumor that the plane could fly upside down was a [10], and the crew had to [11] that idea completely. The snack cart, sadly, was [12] and lost a wheel.',key:['veteran','cancel','continuous','blunder','distribute','solitary','scuffle','document','temporary','myth','reject','fragile']}
  ];
  function esc(v){return String(v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}
  function norm(v){return String(v||'').toLowerCase().trim().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ').replace(/[.!?,;:]$/g,'');}
  function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=x[i];x[i]=x[j];x[j]=t;}return x;}
  function params(){return new URLSearchParams(location.search);}
  function pickLearner(){var q=params().get('learner');if(q==='Luke'||q==='Samantha'){learner=q;showTypes();return;}app.innerHTML='<section class="mock-panel"><p class="eyebrow">Final verification</p><h1>Who is taking the mock?</h1><div class="mock-picker"><button class="primary-button" data-learner="Luke">Luke</button><button class="primary-button" data-learner="Samantha">Samantha</button></div><p class="mock-warning">Mocks give no correctness feedback until the entire test is submitted.</p></section>';app.querySelectorAll('[data-learner]').forEach(function(b){b.addEventListener('click',function(){learner=b.dataset.learner;showTypes();});});}
  function showTypes(){var r=M.readiness(learner);app.innerHTML='<section class="mock-panel"><p class="eyebrow">'+esc(learner)+' · final verification</p><h1>Choose a mock</h1><p>Use these after practice. The mock diagnoses misses; it does not coach during the test.</p><div class="meter-grid"><div class="meter"><strong>'+r.vocab+'/12</strong><span>vocabulary ready</span></div><div class="meter"><strong>'+r.spelling+'/12</strong><span>spelling ready</span></div><div class="meter"><strong>'+r.both+'/12</strong><span>ready in both</span></div></div><div class="mock-type"><button class="mock-type-card" id="start-vocab"><strong>Vocabulary mock</strong><span>12-for-12 paragraph + synonym/antonym back section</span></button><button class="mock-type-card" id="start-spelling"><strong>Spelling mock</strong><span>12 words from dictation · no answer shown until the end</span></button></div><button class="text-button" id="change-learner">Change learner</button></section>';document.getElementById('start-vocab').addEventListener('click',startVocab);document.getElementById('start-spelling').addEventListener('click',startSpelling);document.getElementById('change-learner').addEventListener('click',function(){learner=null;history.replaceState(null,'',location.pathname);pickLearner();});}
  function chooseForm(){var mocks=M.loadMocks(),last=(mocks.learners[learner]||{}).lastVocabForm;return FORMS.find(function(f){return f.id!==last;})||FORMS[0];}
  function paragraphHTML(form,answers,active){return form.text.replace(/\[(\d+)\]/g,function(_,n){var i=Number(n)-1,val=answers[i]||'';return '<button type="button" class="mock-blank '+(i===active?'active ':'')+(val?'filled':'')+'" data-blank="'+i+'" aria-label="Blank '+(i+1)+(val?': '+val:'')+'">'+(val?esc(val):'blank '+(i+1))+'</button>';});}
  function startVocab(){var form=chooseForm();session={type:'vocabulary',form:form,answers:Array(12).fill(''),active:0};renderVocab();}
  function renderVocab(){var s=session,used=new Set(s.answers.filter(Boolean));app.innerHTML='<section class="mock-panel"><p class="mock-progress">'+esc(learner)+' · Vocabulary final mock</p><h1>Front: 12-for-12 paragraph</h1><div class="mock-instructions">Use every word once. Cross words off mentally as you go. No answers are checked until you submit the whole front and back.</div><div class="mock-word-bank">'+M.BANK.map(function(w){return '<button type="button" class="mock-word '+(used.has(w)?'used':'')+'" data-word="'+w+'">'+w+'</button>';}).join('')+'</div><div class="mock-paragraph">'+paragraphHTML(s.form,s.answers,s.active)+'</div><p class="subhead">Back: teacher-sheet relationships</p><p>For each word, type one teacher-sheet synonym and one teacher-sheet antonym. For <strong>document</strong> and <strong>scuffle</strong>, type <strong>none given</strong> for the antonym.</p><form id="vocab-mock-form"><div class="mock-back-grid">'+M.BANK.map(function(w){return '<div class="mock-back-row"><strong>'+w+'</strong><label>Synonym<input data-syn="'+w+'" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false"></label><label>Antonym<input data-ant="'+w+'" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false"></label></div>';}).join('')+'</div><button type="submit" class="primary-button mock-submit">Submit entire vocabulary mock</button></form><p class="mock-warning">Nothing above is graded until Submit.</p></section>';
    app.querySelectorAll('[data-blank]').forEach(function(b){b.addEventListener('click',function(){s.active=Number(b.dataset.blank);renderVocabPreservingBack();});});
    app.querySelectorAll('[data-word]').forEach(function(b){b.addEventListener('click',function(){var w=b.dataset.word,old=s.answers.indexOf(w);if(old>=0&&old!==s.active)s.answers[old]='';s.answers[s.active]=w;s.active=Math.min(11,s.active+1);renderVocabPreservingBack();});});
    document.getElementById('vocab-mock-form').addEventListener('submit',submitVocab);
  }
  function collectBack(){var out={};M.BANK.forEach(function(w){var a=app.querySelector('[data-syn="'+w+'"]'),b=app.querySelector('[data-ant="'+w+'"]');out[w]={syn:a?a.value:'',ant:b?b.value:''};});return out;}
  function restoreBack(values){if(!values)return;M.BANK.forEach(function(w){var a=app.querySelector('[data-syn="'+w+'"]'),b=app.querySelector('[data-ant="'+w+'"]');if(a)a.value=values[w].syn;if(b)b.value=values[w].ant;});}
  function renderVocabPreservingBack(){var back=collectBack();renderVocab();restoreBack(back);}
  function submitVocab(e){e.preventDefault();var s=session,back=collectBack();if(s.answers.some(function(x){return !x;})){alert('Fill all 12 paragraph blanks before submitting.');return;}var missing=M.BANK.some(function(w){return !back[w].syn.trim()||!back[w].ant.trim();});if(missing){alert('Complete every synonym and antonym box. Use “none given” for document and scuffle antonyms.');return;}
    var front=0,syn=0,ant=0,review=[];
    s.form.key.forEach(function(word,i){var ok=s.answers[i]===word;if(ok)front++;M.recordEvidence(learner,word,'definition',ok,{independent:true,type:'mock-context',error:ok?null:'paragraph choice'});if(!ok)review.push({label:'Paragraph blank '+(i+1),given:s.answers[i],expected:word});});
    M.BANK.forEach(function(word){var d=M.DATA[word],synOk=d.syn.some(function(x){return norm(x)===norm(back[word].syn);});if(synOk)syn++;M.recordEvidence(learner,word,'synonym',synOk,{independent:true,type:'mock-synonym',error:synOk?null:'relationship recall'});if(!synOk)review.push({label:word+' synonym',given:back[word].syn,expected:d.syn.join(' / ')});
      var antOk=d.ant.length?d.ant.some(function(x){return norm(x)===norm(back[word].ant);}):norm(back[word].ant)==='none given';if(antOk)ant++;if(d.ant.length)M.recordEvidence(learner,word,'antonym',antOk,{independent:true,type:'mock-antonym',error:antOk?null:'relationship recall'});if(!antOk)review.push({label:word+' antonym',given:back[word].ant,expected:d.ant.length?d.ant.join(' / '):'none given'});});
    var total=36,correct=front+syn+ant,result={type:'vocabulary',at:new Date().toISOString(),correct:correct,total:total,front:front,synonym:syn,antonym:ant,formId:s.form.id};M.recordMock(learner,result);if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);showVocabSummary(result,review);
  }
  function showVocabSummary(result,review){app.innerHTML='<section class="mock-summary"><p class="eyebrow">Vocabulary mock complete</p><div class="mock-score">'+result.correct+'/'+result.total+'</div><p>Front paragraph: <strong>'+result.front+'/12</strong> · Synonyms: <strong>'+result.synonym+'/12</strong> · Antonyms: <strong>'+result.antonym+'/12</strong></p>'+(review.length?'<div class="mock-review"><h2>Send these back to practice</h2>'+review.map(function(r){return '<div class="mock-review-row"><strong>'+esc(r.label)+'</strong><span>You wrote: '+esc(r.given||'blank')+'</span><span class="miss">Expected: '+esc(r.expected)+'</span></div>';}).join('')+'</div>':'<h2>Clean mock.</h2>')+'<div class="learner-actions"><a class="primary-button" href="test-practice.html?learner='+encodeURIComponent(learner)+'">Continue targeted practice</a><a class="secondary-button" href="parent-readiness.html">Parent view</a><button class="text-button" id="mock-again">Choose another mock</button></div></section>';document.getElementById('mock-again').addEventListener('click',showTypes);}
  function startSpelling(){session={type:'spelling',order:shuffle(M.BANK),index:0,answers:[]};renderSpelling();setTimeout(speakCurrent,40);}
  function renderSpelling(){var s=session;if(s.index>=s.order.length){gradeSpelling();return;}app.innerHTML='<section class="mock-panel"><p class="mock-progress">'+esc(learner)+' · Spelling final mock · Word '+(s.index+1)+' of 12</p><div class="mock-spelling-card"><p class="eyebrow">Audio only</p><h1>Listen. Type the word.</h1><p id="audio-status">No spelling answer will be shown until all 12 are finished.</p><button type="button" class="secondary-button hear-word" id="hear-word">Hear word</button><form id="spelling-form"><label class="sr-only" for="spelling-answer">Type the spelling</label><input class="mock-spelling-input" id="spelling-answer" autocomplete="off" autocapitalize="none" autocorrect="off" spellcheck="false" enterkeyhint="next"><br><button type="submit" class="primary-button mock-next">'+(s.index===11?'Finish spelling mock':'Save and hear next word')+'</button></form></div></section>';document.getElementById('hear-word').addEventListener('click',speakCurrent);document.getElementById('spelling-form').addEventListener('submit',function(e){e.preventDefault();var input=document.getElementById('spelling-answer');if(!input.value.trim()){input.focus();return;}s.answers.push(input.value.trim());s.index++;if(s.index>=12)gradeSpelling();else{renderSpelling();speakCurrent();}});document.getElementById('spelling-answer').focus();}
  function speakCurrent(){if(!session||session.type!=='spelling'||session.index>=12)return;var status=document.getElementById('audio-status');if(!('speechSynthesis'in window)){if(status)status.textContent='Audio is unavailable. Ask an adult to read the exact spelling word.';return;}try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(session.order[session.index]);u.lang='en-US';u.rate=1;u.onerror=function(){if(status)status.textContent='Audio is unavailable. Ask an adult to read the exact spelling word.';};speechSynthesis.speak(u);}catch(_){if(status)status.textContent='Audio is unavailable. Ask an adult to read the exact spelling word.';}}
  function gradeSpelling(){var s=session,correct=0,review=[];s.order.forEach(function(word,i){var given=s.answers[i]||'',ok=norm(given)===word;if(ok)correct++;var error=ok?null:M.spellingError(word,given);M.recordEvidence(learner,word,'spelling',ok,{independent:true,type:'mock-spelling',error:error});if(!ok)review.push({word:word,given:given,error:error});});var result={type:'spelling',at:new Date().toISOString(),correct:correct,total:12};M.recordMock(learner,result);if(window.WordExpeditionCloud)window.WordExpeditionCloud.schedule(0);app.innerHTML='<section class="mock-summary"><p class="eyebrow">Spelling mock complete</p><div class="mock-score">'+correct+'/12</div>'+(review.length?'<div class="mock-review"><h2>Words to repair</h2>'+review.map(function(r){return '<div class="mock-review-row"><strong>'+esc(r.word)+'</strong><span>You wrote: '+esc(r.given||'blank')+'</span><span class="miss">'+esc(r.error||'spelling miss')+'</span></div>';}).join('')+'</div>':'<h2>Clean spelling mock.</h2>')+'<p class="mock-warning">The mock is diagnostic. Missed words are now higher priority in adaptive practice.</p><div class="learner-actions"><a class="primary-button" href="test-practice.html?learner='+encodeURIComponent(learner)+'">Repair missed words</a><a class="secondary-button" href="parent-readiness.html">Parent view</a><button class="text-button" id="mock-again">Choose another mock</button></div></section>';document.getElementById('mock-again').addEventListener('click',showTypes);}
  pickLearner();
})();
