(function(){
  'use strict';
  var M=window.WordExpeditionMastery;if(!M)return;
  var CLOUD_URL='https://lpjvsjezjjasgpkvjjlq.supabase.co/functions/v1/studyhub-save';
  var TOKEN_KEY='studyhubCloudToken',LEGACY_TOKEN_KEY='usStatesCloudToken';
  var ENABLED=location.protocol==='https:'&&/(^|\.)stevetodman\.com$/i.test(location.hostname);
  var PROFILE_KEYS={Luke:'word-mission-unit1-luke',Samantha:'word-mission-unit1-samantha'};
  var AVATARS={Luke:'🚀',Samantha:'⭐'};
  var DOMAINS=['definition','synonym','antonym','spelling','pos'];
  var status=ENABLED?'loading':'local',timer=null,inFlight=false,queued=false,lastMain='';

  function token(){try{var t=localStorage.getItem(TOKEN_KEY)||localStorage.getItem(LEGACY_TOKEN_KEY);if(t&&!localStorage.getItem(TOKEN_KEY))localStorage.setItem(TOKEN_KEY,t);return t;}catch(_){return null;}}
  function validToken(t){return !!t&&(/^[0-9a-f]{48}$/i.test(t)||(t.length>=20&&t.length<=200&&/^[A-Za-z0-9_-]+$/.test(t)));}
  function adoptHash(){var m=/(?:^|[#&])k=([^&]+)/.exec(location.hash||'');if(!m)return false;var t;try{t=decodeURIComponent(m[1]).trim();}catch(_){return false;}if(!validToken(t))return false;try{localStorage.setItem(TOKEN_KEY,t);history.replaceState(null,'',location.pathname+location.search);}catch(_){}return true;}
  function setStatus(next){status=next;document.querySelectorAll('[data-mastery-cloud-status]').forEach(function(el){el.textContent=statusText();el.dataset.state=status;});window.dispatchEvent(new CustomEvent('wordexpedition:cloud',{detail:{status:status}}));}
  function statusText(){if(!ENABLED)return 'Saved on this device';if(status==='saving'||status==='loading')return '☁ Saving…';if(status==='saved')return '☁ Saved';if(status==='unlinked')return 'Saved on this device · family link needed';if(status==='capacity')return 'Saved on this device · cloud storage full';return 'Offline · saved on this device';}
  function request(payload){return fetch(CLOUD_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}).then(function(res){return res.json().then(function(body){if(!res.ok){var e=new Error(body.error||('cloud '+res.status));e.status=res.status;throw e;}return body;});});}
  function skillKey(word,domain){return 'wm1|'+word+'|'+domain;}
  function practiceKey(word,domain){return 'wm1p|'+word+'|'+domain;}
  function independentCount(name,word,domain,st){var local=M.recentEvents(name,word,domain).filter(function(e){return e.correct&&e.independent&&!e.assisted;}).length;return Math.max(local,Number(st&&st.practiceIndependent)||0);}
  function payload(){var main=M.loadMain(),out={};['Luke','Samantha'].forEach(function(name){var p=main.learners[name]||{stats:{}},remoteStats={};M.BANK.forEach(function(word){DOMAINS.forEach(function(domain){var st=p.stats[word+'|'+domain];if(st){var base=skillKey(word,domain);remoteStats[base]={streak:st.streak||0,correct:st.correct||0,wrong:st.wrong||0,mastered:false};(st.correctDays||[]).forEach(function(day){if(/^\d{4}-\d{2}-\d{2}$/.test(day))remoteStats[base+'|day|'+day]={streak:1,correct:1,wrong:0,mastered:true};});}var independent=independentCount(name,word,domain,st);if(independent)remoteStats[practiceKey(word,domain)]={streak:independent,correct:independent,wrong:0,mastered:false};});});out[PROFILE_KEYS[name]]={stateStats:remoteStats,masteredOrder:[],avatar:AVATARS[name]};});return out;}
  function syncPracticeEvidence(meta,main,name,word,domain,count){if(!count)return;var p=main.learners[name]=main.learners[name]||{stats:{},sessions:[]},k=word+'|'+domain,st=p.stats[k]||{attempts:0,correct:0,wrong:0,assisted:0,streak:0,correctDays:[],lastAt:null};st.practiceIndependent=Math.max(Number(st.practiceIndependent)||0,count);p.stats[k]=st;var mp=meta.learners[name]=meta.learners[name]||{events:[],diagnostic:null,paragraphClean:false,practiceMs:0};mp.events=mp.events||[];var existing=mp.events.filter(function(e){return e.word===word&&e.domain===domain&&e.correct&&e.independent&&!e.assisted;}).length,need=Math.max(0,count-existing);if(need){var synthetic=Array.from({length:need},function(_,i){return {ts:i,word:word,domain:domain,type:'cloud-independent',correct:true,independent:true,assisted:false,error:null};});mp.events=synthetic.concat(mp.events);if(mp.events.length>600)mp.events=mp.events.slice(-600);}}
  function apply(remote){if(!remote||typeof remote!=='object')return;var main=M.loadMain(),meta=M.loadMeta();['Luke','Samantha'].forEach(function(name){var profile=remote[PROFILE_KEYS[name]],stats=profile&&profile.stateStats;if(!stats||typeof stats!=='object')return;main.learners[name]=main.learners[name]||{stats:{},sessions:[]};main.learners[name].stats=main.learners[name].stats||{};Object.keys(stats).forEach(function(key){var parts=key.split('|'),r=stats[key]||{};if(parts[0]==='wm1p'&&parts.length===3&&M.BANK.indexOf(parts[1])>=0&&DOMAINS.indexOf(parts[2])>=0){syncPracticeEvidence(meta,main,name,parts[1],parts[2],Math.max(Number(r.correct)||0,Number(r.streak)||0));return;}if(parts[0]!=='wm1'||M.BANK.indexOf(parts[1])<0||DOMAINS.indexOf(parts[2])<0)return;var k=parts[1]+'|'+parts[2],local=main.learners[name].stats[k]||{attempts:0,correct:0,wrong:0,assisted:0,streak:0,correctDays:[],lastAt:null};if(parts.length===3){local.correct=Math.max(local.correct||0,Number(r.correct)||0);local.wrong=Math.max(local.wrong||0,Number(r.wrong)||0);local.streak=Math.max(local.streak||0,Number(r.streak)||0);local.attempts=Math.max(local.attempts||0,(local.correct||0)+(local.wrong||0)+(local.assisted||0));}else if(parts.length===5&&parts[3]==='day'&&/^\d{4}-\d{2}-\d{2}$/.test(parts[4])&&r.mastered){local.correctDays=Array.from(new Set((local.correctDays||[]).concat(parts[4]))).sort();}main.learners[name].stats[k]=local;});});M.saveMain(main);M.saveMeta(meta);lastMain=localStorage.getItem(M.MAIN_STORAGE)||'';window.dispatchEvent(new CustomEvent('wordexpedition:mastery-updated'));}
  function handleError(e){setStatus(e&&e.status===403?'unlinked':e&&e.status===413?'capacity':'offline');}
  function pull(){if(!ENABLED)return Promise.resolve(false);var t=token();if(!t){setStatus('unlinked');return Promise.resolve(false);}setStatus('loading');return request({token:t,action:'pull'}).then(function(res){if(res.found)apply(res.data);setStatus(res.found?'saved':'unlinked');return !!res.found;}).catch(function(e){handleError(e);return false;});}
  function push(){if(!ENABLED)return Promise.resolve(false);var t=token();if(!t){setStatus('unlinked');return Promise.resolve(false);}if(inFlight){queued=true;return Promise.resolve(false);}inFlight=true;setStatus('saving');return request({token:t,action:'push',data:payload()}).then(function(res){apply(res.data);setStatus('saved');return true;}).catch(function(e){handleError(e);return false;}).then(function(ok){inFlight=false;if(queued){queued=false;schedule(0);}return ok;});}
  function schedule(delay){if(!ENABLED)return;clearTimeout(timer);timer=setTimeout(function(){timer=null;push();},delay===undefined?900:delay);}
  function watch(){lastMain=localStorage.getItem(M.MAIN_STORAGE)||'';setInterval(function(){if(document.hidden)return;var now=localStorage.getItem(M.MAIN_STORAGE)||'';if(now!==lastMain){lastMain=now;schedule();}},750);}
  function shareLink(){var t=token();return t?location.origin+'/study/#k='+encodeURIComponent(t):null;}

  adoptHash();watch();window.addEventListener('online',function(){pull().then(function(){schedule(0);});});document.addEventListener('visibilitychange',function(){if(!document.hidden)pull();});
  window.WordExpeditionCloud={enabled:ENABLED,status:function(){return status;},statusText:statusText,pull:pull,push:push,schedule:schedule,token:token,shareLink:shareLink,payload:payload,apply:apply};
  pull();
})();
